### ISSUE TITLE
Explain how we utilise Draft Pull Requests to communicate each other (with screenshots)

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#100]
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request

**Comment by ekafyi** [comment]
*(slightly related)* 
If anyone needs refresher/quick "copypasta" on fetching from origin while working on a forked branch (so we can constantly push to the Draft PR and resolve conflicts as we go), I wrote a post on it: https://dev.to/ekafyi/pull-fetch-from-a-forked-github-repository-1p9p
