### ISSUE TITLE
Add minor mobile UI improvement in province pages

### ISSUE THREAD

**Issue by ekafyi** [kawalcovid19/wargabantuwarga.com#104]
## Description

Add minor UI improvement in province pages that enhances readability, especially in mobile/small screen views.

1. update list headings font weight from 500 (`font-medium`) to 600 (`font-semibold`)
2. remove "pada" in "Terverifikasi pada" (detail below)
    - 2b. switch icon order to left in mobile views
3. align location icons to top

Rationale for removing "pada" in "Terverifikasi pada" copy text:
- datetime is not always present
- if present, the text still makes sense "Terverifikasi 17 Juli 2021"
- more concise

(1) list heading font weight example

![www_wargabantuwarga_com_provinces_dkijakarta-1_Moto_G4___2__png_and_www_wargabantuwarga_com_provinces_dkijakarta-1_Moto_G4___1__png](https://user-images.githubusercontent.com/6597211/126031484-fa4ef22d-1c7b-4465-a7ae-a76da472857b.png)

(2) - (3) example

![Screen Shot 2021-07-17 at 15 25 31](https://user-images.githubusercontent.com/6597211/126031493-88265585-3b9b-41fd-8948-853b788a6fa7.png)

Related to #68

## Implementation Model

Update Tailwind CSS classes, add custom styles if needed.

Ready to provide PR if approved.

**Comment by zainfathoni** [comment]
Sounds great, please go ahead with your implementation @ekafyi! Thanks! 🙏
