### ISSUE TITLE
Explain why we're using English in GitHub Issues & PRs

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#108]
The reasons we're using English in GitHub Issues & PRs:

1. It's more natural for software engineers to communicate in English because it involves many technical terms in English. Trying to translate them into Bahasa Indonesia posing a risk of miscommunication, while keeping them in English requires us to do a lot of _italic_ formatting, according to [PUEBI](https://puebi.js.org/huruf/miring).
2. It accustoms the contributors, which are mostly Indonesian, to communicate in English. It is important to increase our English reading and writing skills because the vast majority of the global open-source communities are using Engish as the main language.
3. It makes this project easier to be recognised globally. So if we need to get more support from the global communities, they could easily understand what we are doing and help us out with their access and competence. e.g., providing us free credits for their services, advocating us to global leaders, or contributing directly to our codebase.

**Comment by andriawan** [comment]
i'm not quite understand the reason behind this mas @zainfathoni. Could you enlighten me mas @zainfathoni ?

**Comment by zainfathoni** [comment]
I have updated the description with my explanation, @andriawan. 😁
