### ISSUE TITLE
Use a proper client-side search engine library to power the search functionality in our pages

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#111]
For better search results, maybe a full-text search can be used?

The potential libraries are:
- https://www.npmjs.com/package/itemsjs (with aggregation to support the filter)
- https://www.npmjs.com/package/minisearch
- https://fusejs.io/

**Comment by ekamuktia** [comment]
I'm currently experimenting itemsjs for the search, some things to note:
- The aggregation feature can be used for filter, but it's case sensitive and need exact term. Some of the data contain trailing spaces and same text with different variations (eg. Jakarta Barat, Jakarta barat). Need to decide whether the data will be cleaned on the source or on the application.
![image](https://user-images.githubusercontent.com/9606523/126057825-dc114b15-f7af-4c77-a21e-38592f2f00e9.png)
- Sort can be easily set up (can be helpful if we add sort by feature)
- There's no function like extractField in Mini Search, so if need it then we need to extend it ourselves. (for example when adding Verified column on the data to be indexed)

**Comment by zainfathoni** [comment]
> Need to decide whether the data will be cleaned on the source or on the application.

For the first phase, we can't rely on the cleaning up from the source sheets, because it is done manually. We should try cleaning it up on our side as much as possible.
However, in the future, we can try to implement a proper **Data Validation** mechanism in the Google Sheet. I need to talk to Mas Awe about it.

> Sort can be easily set up (can be helpful if we add sort by feature)

Yes, please. Btw, based on #131, we shouldn't provide `Terverifikasi` filter and sort options for the users, but we should always prioritise the verified ones over the non-verified ones.

> There's no function like extractField in Mini Search, so if need it then we need to extend it ourselves. (for example when adding Verified column on the data to be indexed)

Then let's focus on the `itemsjs` first. Moreover, please try to minimize its performance impact into our website by importing the library dynamically if possible. Thanks!

Btw, could you please submit a **Draft Pull Request** and link it to this issue to signal other contributors that you have started working on it? Thanks, Mbak @ekamuktia!

**Comment by ekamuktia** [comment]
@zainfathoni Okay, sure! I'll work on this part then
