### ISSUE TITLE
SEO Improvement for Province & Contact Pages

### ISSUE THREAD

**Issue by ekamuktia** [kawalcovid19/wargabantuwarga.com#115]
## Description

Improve SEO strategy for province & contact page for better searchability

## Implementation Model

- Use Next SEO to set page meta & open graph data
- Deciding the rule/pattern for each page meta/open graph title & description
For example: 
On province page, the title use "Informasi Faskes & Alkes untuk COVID-19 di Provinsi (Nama Provinsi)" rule
On contact page, with "(Penyedia) - (Keterangan) di (Lokasi)" rule e.g. "Ambulans rumah sakit advent - Ambulans di Bandar Lampung"
Still have no idea for description part. Need suggestion from SEO expert, also need to consider character length for both title & description.
- Change slug for contact page
Currently there's no id on each contact data, and the slug is based on row order. 
I'm not sure how the data is updated, but if a row is removed on the source sheet and a user already shared the contact page url, the url may link to different contact from what the user intended.
Using slug from contact penyedia name can be a better option, as it's more SEO friendly too. But, if this data can be updated, then different strategy should be considered.
- Add title property on the link (esp. internal one)
- Give rel="nofollow" to external links
- Create sitemap.xml

**Comment by mazipan** [comment]
For sitemap, you can try to use [next-sitemap](https://www.npmjs.com/package/next-sitemap).

I think it will be simpler for us
