### ISSUE TITLE
Add error pages (404, etc.)

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#127]
## Description

Replace the default Next.js Error pages with a customised version tailored for our design

## Implementation Model

[Tailwind UI](https://tailwindui.com/components/marketing/feedback/404-pages) now has examples for error pages (mainly 404 page). We can base it off there for the time being.

## Tasks

- [x] 404 page (`/pages/404.tsx`) #135 
- [ ] Fallback Error page (`/pages/_error.tsx`)

**Comment by hanihusam** [comment]
Can I get this one, Mas?

**Comment by resir014** [comment]
@hanihusam sure!

**Comment by zainfathoni** [comment]
Reopening this issue because the `/pages/_error.tsx` page has not been implemented yet.

**Comment by zainfathoni** [comment]
Oops, my bad. I just realised that your PR also contains the `/pages/_error.tsx` implementation. 😅 

Closing this issue again. 😁
