### ISSUE TITLE
Add canonical link to next-seo

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#158]
## Description

We tried adding `canonical` URL for SEO improvements with `next-seo` on #150 earlier, however Lighthouse SEO score took a hit during deploy preview so we had to remove it. Find a way to get it back without impacting Lighthouse score,

![image](https://user-images.githubusercontent.com/5663877/126128602-50f40b72-1641-4937-9c06-66141b6008bd.png)

## Implementation Model

This (potentially) happens since we're not using the valid domain name for canonical link. With my initial implementation everything is hardcoded to `https://www.wargabantuwarga.com`.

~~Further research is needed.~~ Research complete. We can go ahead with this, however we can't reliably guarantee netlify build will succeed unless we 1) temporarily reduce Lighthouse threshold; or 2) complete #198.

## Tasks

- [x] Add canonical link via `next-seo` with the exact link for each page.
- [x] Allow setting `site_url` config via Netlify CMS

**Comment by mazipan** [comment]
![Screenshot_20210721-064951_Chrome](https://user-images.githubusercontent.com/7221389/126409132-f608e299-469f-415b-b5d1-890de3e1f966.jpg)


Why is the Canonical Link matter?
Look on the screenshot, the URL with an additional parameter can be determined as a different URL by a Google Bot.
When we set a canonical link, Google will know that this kind of URL is a same type.

**Comment by mazipan** [comment]
Is there any way to reproduce this message on the local machine without need to run the Deploy on the Netlify @resir014?

**Comment by resir014** [comment]
> But about a warning on the Netlify, it's different things. Maybe because Netlify set a preview URL with a random generated URL

@mazipan Yes, that's my initial suspicion. Netlify Lighthouse doesn't seem to like it when we hardcode the `www.wargabantuwarga.com` URL in the canonical link element, causing it to drop our score.

I guess when we finally split Lighthouse from the Netlify build step (#198), we should have no problem re-adding the canonical link without Lighthouse screaming at our ears about invalid canonical link.

**Comment by resir014** [comment]
Issue + tasks list updated.
