### ISSUE TITLE
Adding GTM to enable us to track information click rate on the wargabantuwarga

### ISSUE THREAD

**Issue by baraeb92** [kawalcovid19/wargabantuwarga.com#18]
## Description

We probably need to start adding analytical tools to wargabantuwarga.com, because has multiple information entry, we need to track which clicks or which information is most relevant to the user, this will eventually be useful for us to enhance the information structure of the web, to ensure the most important information is displayed first. 

Job Story

When the user is accessing, I want the Google Tag Manager to be triggered there, so that we can track each user’s clicks to gather data about user navigation. 

Acceptance Criteria

Use the following criteria example

Functional Criteria: "GTM with id **GTM-5X4ZPBX** to be triggered on this page"

Non-functional Criteria: "Paste this code as high in the `<head>` of the page as possible:

`<!-- Google Tag Manager --><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5X4ZPBX');</script><!-- End Google Tag Manager --> "`

Non-functional Criteria: Additionally, paste this code immediately after the opening `<body>` tag: `<!-- Google Tag Manager (noscript) --><noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5X4ZPBX"height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><!-- End Google Tag Manager (noscript) -->`

Performance Criteria: "To have minimum impact on performance use the **afterInteractive** or **onLazyLoad** see:  [](https://nextjs.org/docs/basic-features/script
) https://nextjs.org/docs/basic-features/script

Require A QA To Test? 
Yes

Optional Information
Here is the GA4 ID: 278712353

## Current Tasks

- [x] #36
- [x] Integrate GA property into the GTM
- [x] Setup click event triggers on GTM

**Comment by zainfathoni** [comment]
<img width="1026" alt="Screenshot 2021-07-09 at 23 16 04" src="https://user-images.githubusercontent.com/6315466/125100588-d9ce5500-e10b-11eb-83cb-f7804aeb3fc6.png">

GTM is successfully integrated [without any performance degradation](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.wargabantuwarga.com%2F), bravo!.
