### ISSUE TITLE
Replace Netlify Lighthouse

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#198]
## Description

The main problem when we put the performance test on the build process is that it will slow down our build time. So the idea is to differentiate the process.

Move the performance check from build time to the PR creation without blocking the build process. It block the PR, not the build process.

## Proposal

Try to check Lighthouse-CI on GitHub Action: https://github.com/GoogleChrome/lighthouse-ci

**Comment by mazipan** [comment]
@zainfathoni Request to add SECRET on the Github Action

ref: https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md#overview

**Comment by mazipan** [comment]
Request install App ini ya: 

https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/getting-started.md#github-app-method-recommended

**Comment by zainfathoni** [comment]
App installed and `secrets.LHCI_GITHUB_APP_TOKEN` set Mas @mazipan. Thanks for working on it!
