### ISSUE TITLE
Data - Double DKI Jakarta

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#208]
## Description

The data seems need to be clean up, so we can grouping it better

## Step to reproduce

- Visit: https://www.wargabantuwarga.com/provinces/dkijakarta-1
- Click the combobox/select box "Lokasi"
- There are two "DKI Jakarta" data

## Expected

Only one data "DKI Jakarta" or even it should be detailed as Jakarta Pusat/Barat/Selatan/Utara or Kepulauan Seribu.

## Preview

![Screenshot_20210720-153731_Chrome](https://user-images.githubusercontent.com/7221389/126289681-9dc386cf-01ff-49cb-bb75-a828ee773cf1.jpg)

**Comment by zainfathoni** [comment]
Sure, I'll be working on it once I'm granted edit access to the sheets.

**Comment by zainfathoni** [comment]
Issue resolved.

<img width="599" alt="Screenshot 2021-07-21 at 06 58 55" src="https://user-images.githubusercontent.com/6315466/126405791-b364133b-c2e9-4fe2-9ba3-a6559476cf7a.png">
