### ISSUE TITLE
Create a design system / reusable component library for WBW

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#209]
## Overview

~~Because it's not a project with me in it without some work relating to design system.~~

Recently, I've started putting some reusable components inside the `components/ui` folder. We should expand these into more atomic components that we currently use throughout the app.

Yes, I know we use [Tailwind CSS](https://tailwindcss.com/) and [Tailwind UI](https://tailwindui.com/), but over time, we should collect all the stuff that we take from Tailwind UI into a reusable component, so that no duplication is made when we make new pages/screens.

Currently, our goal is to package all the components that we have right now into a reusable component with easy-to-understand, well-documented props. After this epic is complete + closed, continued effort shall be made to update the design system to meet future needs.

## Acceptance criteria

- A design system library is set up in the `components/ui` folder.
- The components have easy-to-understand, well-documented props.
- The design is used in significant parts of the app.

## Current Tasks

- [x] #212
- [x] #213
- [x] #214
- [x] #215
- [x] #216

**Comment by zainfathoni** [comment]
> ~~Because it's not a project with me in it without some work relating to design system.~~

Nice motivation 🤣

**Comment by resir014** [comment]
Since all the tasks here have been completed, we can safely close this issue. 🎉 

Do note that we still continue our effort to update the design system, since our design system shall also evolve to meet future needs. Any new issues + epics regarding to the design system shall be posted under the [`ui` label](https://github.com/kawalcovid19/wargabantuwarga.com/labels/ui).
