### ISSUE TITLE
Add additional information when searching data result is none

### ISSUE THREAD

**Issue by andriawan** [kawalcovid19/wargabantuwarga.com#210]
## Description

Some users might be confused when they don't get information (because of no information could be served) or because no data related to the input.

## Implementation Model

![image](https://user-images.githubusercontent.com/13099373/126297563-496c90cc-e777-4e27-b3b0-81ededd78f01.png)

## Tasks

- [ ]  Provide default UI component for no data

**Comment by ekamuktia** [comment]
For `Province` page maybe we can also show button linked to google form to submit new contact information.
So it will be something like "Tidak ada data untuk keyword yang anda cari. Tambahkan info disini"

"Tambahkan info" button can be added on the default view as well.

**Comment by resir014** [comment]
Fortunately, Tailwind UI [has a component for that](https://tailwindui.com/components/application-ui/feedback/empty-states#component-42930c785190e14c24b53ba822f4a92c).

![image](https://user-images.githubusercontent.com/5663877/126302786-794f09c2-a5d5-4ce1-9bdc-f414aaaf79fc.png)

I can start working on this in a moment.
