### ISSUE TITLE
Fix UX writing for loading state

### ISSUE THREAD

**Issue by famasya** [kawalcovid19/wargabantuwarga.com#222]
## Description
Currently, _loading state_ while data load is ambiguous (attached below). For accessibility, it's better to rephrase the UX writing to represent what's happening.

![Screen Shot 2021-07-20 at 19 27 14](https://user-images.githubusercontent.com/12300316/126324385-49a774c2-2f53-4698-8feb-a293463c260c.jpg)

## Implementation Model
- Differentiate between "not found" state and "loading" state.
- Give loading indicator while fetching data for the first time.

**Comment by mazipan** [comment]
Also happens on other page such as FAQ

**Comment by ihsanrabb** [comment]
Could I work on this, mas @zainfathoni ?

**Comment by zainfathoni** [comment]
Yes, of course.

Just create a Draft Pull Request as mentioned in our [contributing guidelines](https://kcov.id/wbw-contributing).
Thanks!
