### ISSUE TITLE
Text Overflow in Link

### ISSUE THREAD

**Issue by andriawan** [kawalcovid19/wargabantuwarga.com#224]
## Description

![image](https://user-images.githubusercontent.com/13099373/126338127-2c96b7c1-e3a4-4eae-a981-e1462fbc86bd.png)

## Expected Behaviour

the link should not be overflowing the container

## Additional Information

it might be better to use another approach like implementing layout as column rather than row to accomodate long text

**Comment by mazipan** [comment]
Also ideally the link should be shortened by the content writer 😂

**Comment by zainfathoni** [comment]
Okay, another point for me to talk about with Mas Awe. 😅

**Comment by mazipan** [comment]
![Screen Shot 2021-07-21 at 11 28 44](https://user-images.githubusercontent.com/7221389/126431012-c37d5a7c-a921-4292-9f3a-77753c2e8626.png)

Happened on other data

**Comment by mazipan** [comment]
This can be done if we revamp the UI also, not showing it as a grid like this :-D
I think we will wait for #31 first to do a fully revamp, isn't it @zainfathoni? Or can we ask for some UX folks to check this page? Since this page is not related with CMS

**Comment by resir014** [comment]
@zainfathoni @mazipan I think we should remind the content writers to use shortened links for places, etc. where it feels like the original link would overflow.

Some apps provide a shortened link when you use their built-in Share functionality, e.g. Google Maps:

![image](https://user-images.githubusercontent.com/5663877/126446399-86ef1411-a5b1-42ef-99e3-4f4893c19016.png)

**Comment by zainfathoni** [comment]
Okay, I'll take a note of it and discuss it with Mas @ardiwilda later. Thanks for the suggestions @resir014 & Mas @mazipan. 🙏

**Comment by ekafyi** [comment]
> This can be done if we revamp the UI also, not showing it as a grid like this :-D

We can do a quick fix—before any major UI revamp/chance—by adding `.w-full` (`width: 100%`) to the parent element and overriding the `.softmerge-inner` width to `auto` via external CSS.

![Sunan_Jaya_Gas_-_Kontak_dan_Tempat_Oksigen_Tabung_di_Banten___Warga_Bantu_Warga](https://user-images.githubusercontent.com/6597211/126521429-8ca5d6e8-30b7-4ef5-90fa-6fb188cee1bf.png)

(Also a good opportunity for first-time contributors, esp. pure frontend devs who focus on markup & styling)
