### ISSUE TITLE
Dev Experience: Absolute imports and module path alias

### ISSUE THREAD

**Issue by faizrktm** [kawalcovid19/wargabantuwarga.com#225]
## Description

Adding/configure absolute imports and module path alias for readability and easier to write for deep and scattered reference.

## Implementation Model

Using `~/` as a leading character for the local module as a distinguishment between the 3rd party lib.

example:

from
import { LayoutRoot } from "../../../components/layout/layout-root";

to
import { LayoutRoot } from "~/components/layout/layout-root";

## Tasks

- [ ] Initial configuration in tsconfig.json 
- [ ] Update current modules path reference

**Comment by resir014** [comment]
I think let's use `~/` instead (e.g. `~/components`) - or have the option to choose between the two.

**Comment by faizrktm** [comment]
sure, let's use that format, I think its more clear to distinguish and still got the benefit from the absolute import. Thanks @resir014
