### ISSUE TITLE
Move "Warga Bantu Warga" to the back

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#233]
> "Warga Bantu Warga" part takes too much space. How about moving it to the back instead?

It's on the default SEO set by @resir014 & @zainfathoni before.
On the common usecase, the identity sitename is usually on the right side.
After the main title.

So ya, I agree to move it out to the back.

I think it's better to work on another PR ya for fixing the composition of title

_Originally posted by @mazipan in https://github.com/kawalcovid19/wargabantuwarga.com/issues/227#issuecomment-883567404_

**Comment by mazipan** [comment]
You can update `_app.tsx` on the `DefaultSeo` tag and `titleTemplate` attribute.

https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/pages/_app.tsx#L39

**Comment by suliskh** [comment]
So it is supposed to be `"Informasi Faskes & Alkes ... | Warga Bantu Warga"`, isn't it, Mas @zainfathoni @mazipan?
