### ISSUE TITLE
SEO Strategy To Reach More People

### ISSUE THREAD

**Issue by andreasbudiman** [kawalcovid19/wargabantuwarga.com#24]
<html>
<body>

No | Aspect | From | To | Reason
-- | -- | -- | -- | --
1 | Title Tag | Warga Bantu Warga | Warga Bantu Warga \| Informasi Faskes   & Alkes Untuk Covid 19 | It provides more clarity and comply   widely known SEO standards
2 | Meta Description | Inisiatif warga untuk berbagi informasi seputar fasilitas   kesehatan dan alat kesehatan untuk COVID-19 | Inisiatif warga untuk berbagi informasi seputar fasilitas   kesehatan & alat kesehatan untu COVID-19. WargaBantuWarga memudahkan   publik mencari & mengakses informasi | Better appearance and description on   Google Search
3 | H1 pada image | Saat ini image tidak mengandung H1 | Beri H1 pada image di bagian atas | Every page must have 1 h1 and contain target keyword related   to the page
4 | Ubah H1 Menjadi H3 | H1: Daftar Isi | h3: Daftar Isi | Better structure (from Google point of view)
5 | Ubah H1 Menjadi H2 | h1: Situs Informasi Kontak Penanganan COVID-19: Pemerintah dan   Inisiatif Warga | h2: Situs Informasi Kontak Penanganan COVID-19: Pemerintah dan   Inisiatif Warga | Better structure (from Google point of view)
6 | Ubah H1 Menjadi H3 | h1: Daftar Kontak Fasilitas Alat Kesehatan per Provinsi (   Lihat selengkapnya di sini ) | h3: Daftar Kontak Fasilitas Alat Kesehatan per Provinsi (   Lihat selengkapnya di sini ) | Better structure (from Google point of view)
7 | Ubah H1 Menjadi H3 | h1: Isolasi Mandiri: Apa yang harus dilakukan? | h3: Isolasi Mandiri: Apa yang harus dilakukan? | Better structure (from Google point of view)
8 | Ubah H1 Menjadi H3 | h1: Laman Edukasi COVID-19 | h3: Laman Edukasi COVID-19 | Better structure (from Google point of view)
9 | Ubah H1 Menjadi H3 | h1: Donasi dan Penggalangan Dana | h3: Donasi dan Penggalangan Dana | Better structure (from Google point of view)
10 | Ubah H1 Menjadi p atau div | Ada space kosong dengan menggunakan h1 | ubah menjadi p atau div | Empty space better use p or div (as long as not use heading no   problem)
11 | OpenGraph Title | Warga Bantu Warga | Warga Bantu Warga \| Informasi Faskes & Alkes Untuk Covid   19 | Better description on Social Media and when user share on   WhatsApp
12 | OpenGraph Description | Inisiatif warga untuk berbagi informasi seputar fasilitas   kesehatan dan alat kesehatan untuk COVID-19 | Inisiatif warga untuk berbagi informasi seputar fasilitas   kesehatan & alat kesehatan untu COVID-19. WargaBantuWarga memudahkan   publik mencari & mengakses informasi | Better description on Social Media and when user share on   WhatsApp

</body>
</html>
13. Give rel="nofollow" to all external links

---

# Task List
- [x] #26
- [x] #27
- [x] #28
- [x] #29
- [x] #44

**Comment by zainfathoni** [comment]
Thank you for the suggestions Mas @andreasbudiman.
However, could you please format your input into a table like this for the sake of readability?

| No | Aspects   | From              | To                                                           | Reasons                                                        |
|----|-----------|-------------------|--------------------------------------------------------------|----------------------------------------------------------------|
| 1  | Title Tag | Warga Bantu Warga | Warga Bantu Warga \| Informasi Faskes & Alkes Untuk Covid 19 | It provides more clarity and comply widely known SEO standards |
| 2  |           |                   |                                                              |                                                                |
| 3  |           |                   |                                                              |                                                                |

You can use this [Markdown Tables generator](https://www.tablesgenerator.com/markdown_tables#) to generate the table.

**Comment by baraeb92** [comment]
Kalau bisa ditambahin Open Graph suggestionnya juga even better mas.

**Comment by zainfathoni** [comment]
Saya sudah implementasi semua poin dari no. 1 s.d. no. 12 ya Mas @andreasbudiman, tolong bantu cek apakah sudah sesuai dengan yang seharusnya atau belum, makasih. 😁 

Khusus untuk poin no. 13, sepertinya belum bisa kita lakukan dulu untuk saat ini, karena kita masih menggunakan Google Docs sebagai CMS-nya, di mana kita tidak punya kendali atas atribut `rel="nofollow"`-nya.

Kami akan catat ini sebagai issue baru dan perbaiki ini ketika sudah saatnya migrasi ke _Headless CMS_ pengganti Google Docs. 🙏

**Comment by zainfathoni** [comment]
<img width="623" alt="Screenshot 2021-07-09 at 00 54 54" src="https://user-images.githubusercontent.com/6315466/124961632-4c79fa80-e050-11eb-9b32-a4f72d2a1d51.png">

Nampaknya perubahan saya barusan sudah langsung berpengaruh di Google. Terima kasih banyak atas sarannya Mas @andreasbudiman 👍

**Comment by hendraaagil** [comment]
All task for this issue is already done
