### ISSUE TITLE
Add progress bar when transitioning between pages

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#241]
## Description

Add a loading progress bar to the top of the page to communicate to the user that the next page is loading, improving the UX significantly.

## Implementation Model

We can use [nprogress](https://ricostacruz.com/nprogress/) and use Next.js' [Router Events](https://nextjs.org/docs/api-reference/next/router#routerevents). Official example from Next.js is available [here](https://github.com/vercel/next.js/tree/canary/examples/with-loading).

## Tasks

- [ ] Install nprogress
- [ ] Implement nprogress loading bar following [this example](https://github.com/vercel/next.js/tree/canary/examples/with-loading)

**Comment by mazipan** [comment]
Add additional info: 

https://bundlephobia.com/package/nprogress@0.2.0

**4kB** Minified
**1.7kB** Minified + Gzipped
