### ISSUE TITLE
Remove /provinces/tentang-database-0 from sitemap

### ISSUE THREAD

**Issue by ekamuktia** [kawalcovid19/wargabantuwarga.com#242]
## Description
https://www.wargabantuwarga.com/provinces/tentang-database-0 is included in [sitemap](https://www.wargabantuwarga.com/sitemap-3.xml)

![image](https://user-images.githubusercontent.com/9606523/126454002-6485c4b9-3bc2-40b8-8f11-7c11edb6d26b.png)

![image](https://user-images.githubusercontent.com/9606523/126454064-7fa8946e-d04f-4752-9f97-0bd6c0a7f479.png)

## Expected Behaviour

The page should be excluded from sitemap since it's an invalid url

## Additional Information
The first element in province data is {"id":"358239346","name":"Tentang Database","data":[]}
When `getProvincesPaths` is called the path for this data is created. Please exclude the first element from the result.

**Comment by mazipan** [comment]
I think it's better to exclude from the fetcher.
The data should not empty.
