### ISSUE TITLE
Revisit the cronjob frequency

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#246]
## Description

We have a cronjob to deploy the UI for every 15 minutes.

And since our static page is quite huge (3.1K+ 💪), the build process on GitHub Action takes 12-13 minutes to be done. See the screenshot.

I think we need to reduce the frequency.

![Screenshot_20210721-181346_Chrome](https://user-images.githubusercontent.com/7221389/126480076-3f297af4-8d9f-4a7b-b74f-3e911832a7f5.jpg)

## Implementation Model

Update the cronjob string, you can use https://crontab.guru to check the string.

**Comment by zainfathoni** [comment]
Do you think [every 30 minutes](https://github.com/kawalcovid19/wargabantuwarga.com/commit/2dbb1d0f3a526e5b595503d047ba60eade23ddf7) is enough, Mas @mazipan ?

**Comment by mazipan** [comment]
For now yes, just increase incrementally.

But maybe for some time range, like in the midnight, we can decrease the frequency (idk it's possible or not 😂)

**Comment by mazipan** [comment]
We can set multiple cronjob, e.g:

```yaml
on:
  schedule:
    - cron: 0 4-6 * * *
    - cron: 2,10 4,5 * * *
```

Read on: https://github.community/t/multiple-schedules-for-workflow/154811

I think we can set some hour, like: https://crontab.guru/#*/15_8,9,10,11,12,13,14_*_*_*
