### ISSUE TITLE
Hide progress bar on shallow routing

### ISSUE THREAD

**Issue by ekamuktia** [kawalcovid19/wargabantuwarga.com#277]
## Description

On pages with search feature, the url is updated after keyword/filter/sort is changed using shallow routing. 
The progress bar is quite distracting in these pages.

## Expected Behaviour

Progress bar should not show on shallow routing event, especially because loading state for search will be managed separately.

## Additional Information

![201659](https://user-images.githubusercontent.com/9606523/126516926-b423d88f-50f6-4fd0-916d-8d8593e337d4.gif)

**Comment by mazipan** [comment]
How do you think if we update the URL only `onBlur` the input element?
