### ISSUE TITLE
Same-page anchor reference is hidden behind the header

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#298]
## Description

Our current implementation for #285 is not perfect, because when the user clicks the anchor link, the page scrolls to the element with the `id` and putting it at the very top of the page. It makes the title is hidden beneath the header.

As illustrated in this video:

https://user-images.githubusercontent.com/6315466/126579891-e32f2376-55ee-4b4a-b9a0-a35ac4f12a04.mov

## Expected Behaviour

The page should scroll to the section while still showing the title right below the header.

## Additional Information

I solved the same issue in my https://www.ninjavan.co website by adding a dummy element on top of the heading element and style it a few `rem` above the actual heading element.

**Comment by zainfathoni** [comment]
@kawalcovid19/wbw do you have any better idea than mine to solve this problem? 😅

**Comment by ekamuktia** [comment]
based on [this](https://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header), css only solution:

`.home-page-content [id]:before {
  content: '';
  display: block;
  position: relative;
  width: 0;
  height: 6rem;
  margin-top: -6rem
}`

https://user-images.githubusercontent.com/9606523/126593153-fb1ded13-ef16-448d-a264-de5d31a35b3e.mp4
haven't checked with different browser
