### ISSUE TITLE
Migrate the home page from Google Docs to Netlify CMS

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#31]
## Overview

Based on the Website Improvements #23 discussion, we are planning to migrate our Google Docs-based CMS into a proper Headless CMS. This would provide more granular controls over the HTML structure that we're rendering on the page that allows us to style the website flexibly.

## Implementation Model

- Use [Tina Cloud](https://tina.io/cloud/) as the WYSIWYG headless CMS and store the content into Markdown files within this repository.

## Current Tasks

- [x] ~#37~
- [x] #45
- [x] #109
- [x] #118 
- [x] #38
- [x] #62
- [x] #285
- [x] #39

**Comment by resir014** [comment]
I think we need to expedite these. Unfortunately the HTML content that we pull from gdocs doesn't follow proper HTML hierarchy, as mentioned here:

![image](https://user-images.githubusercontent.com/5663877/126035478-397f9671-b7ee-41b6-85fe-5bc2ee345460.png)

https://twitter.com/ginseladipura/status/1416343727790985221

---

Some people also complained about too many texts in the homepage.

![image](https://user-images.githubusercontent.com/5663877/126035476-fcaf265c-f644-4af2-b20c-1ecd215ebb04.png)

https://twitter.com/deus_xmchn/status/1416291634216673280

**Comment by zainfathoni** [comment]
Agreed. Once we finished with #87, this should be our top priority. 💪

**Comment by resir014** [comment]
A quick fix for the time being is to utilise `@tailwindcss/typography`:

https://tailwindcss-typography.netlify.app/

**Comment by zainfathoni** [comment]
Got it, thanks! Issue created at #109.

**Comment by mazipan** [comment]
So the page under Netlify CMS is on:

- https://www.wargabantuwarga.com/home-page

And the current version is on:

- https://www.wargabantuwarga.com/

**Comment by resir014** [comment]
@mazipan Yes, agree. I think before we fully swap the home page to the Netlify CMS version, we should split the homepage contents first, so we could easily break up each section of the homepage like the planned design on the Figma.

cc: @zainfathoni

**Comment by zainfathoni** [comment]
From the potential changes based on Figma design, do you have any suggestions on how we should split the sections into @resir014?

**Comment by resir014** [comment]
@zainfathoni I already have some mapping in my head right now:

- Welcome Message (single page, rendered on dialog)
- Cara Berkontribusi (single page)
- Informasi Terbaru (multiple posts)

Stuff that's on a separate page

- Kontak darurat (multiple items)
- Tentang Kami (single page? multiple items?)
- Edukasi (multiple items + sub-items)
- Telemedicine (single page w/ metadata)

Stuff that I'm not certain how to split up yet, or if we should make the content for it:

- Donasi Warga (are we pulling from another API? if not, we can create a section on Netlify CMS which aggregates those links)
- Isolasi Mandiri (not sure where to put this?)

**Comment by zainfathoni** [comment]
> For now, we can flip the switch so that the Netlify CMS page becomes the actual homepage. Then we can slowly break away things and create some kind of a "Home Page 2.0" page with all the stuff that's already broken down into sections.

Yes, that's my initial idea.

Wanna have a call tonight @resir014? We can flip the switch together while discussing about the migration to v2.0

**Comment by resir014** [comment]
@zainfathoni I'm available but only before 20:30. Maybe let's try earlier?

**Comment by zainfathoni** [comment]
Sure! I just announced it over here:
https://twitter.com/zainfathoni/status/1418138662223552517?s=20
