### ISSUE TITLE
Add guide for contributors related to fork repository mechanism

### ISSUE THREAD

**Issue by andriawan** [kawalcovid19/wargabantuwarga.com#318]
to propose a change, contributors should follow guide about [forking mechanism](https://docs.github.com/en/get-started/quickstart/fork-a-repo). I think we could state it in README for clarity

**Comment by fncolon** [comment]
how about state it in #319 separated files?

**Comment by zainfathoni** [comment]
@andriawan could you please track this issue inside the related epics for the sake of discoverability?

I have invited you as a Collaborator to the repository so you can edit the epic issue descriptions by yourself to do so.

Thanks, @andriawan!

**Comment by apraditya** [comment]
@zainfathoni, now that #319 is merged & closed, is there anything else left to be done for this issue?

**Comment by andriawan** [comment]
I think it could be taken mas @apraditya

**Comment by apraditya** [comment]
I don't quite get it @andriawan. Do you think we can close this issue?

**Comment by andriawan** [comment]
I think adding this infromation to documentation is quite important for new comer as i found several contributors is not quite familiar with forking mechanism

**Comment by zainfathoni** [comment]
> I don't quite get it @andriawan. Do you think we can close this issue?

No, he meant that you could take this issue, @apraditya. @andriawan, please try to avoid passive sentences as much as possible to avoid ambiguity. Your "it could be taken" sentence is unclear on who gets to take the issue. 😅 

Please create a **draft pull request** as explained in our [contributing guidelines](https://kcov.id/draft-pr).

**Comment by andriawan** [comment]
sorry, i lost the context mas @zainfathoni. Sorry for my miss understanding 😅  🙏🏼  @zainfathoni @apraditya
