### ISSUE TITLE
Separate the CONTRIBUTING.md file based on ID and EN translation

### ISSUE THREAD

**Issue by fncolon** [kawalcovid19/wargabantuwarga.com#319]
Separate the CONTRIBUTING.md file into `CONTRIBUTING_ID.md` and `CONTRIBUTING.md` , considering that the majority of contributors here are Indonesian and we cannot translate them into languages other than those two languages.

the benefit of this is that it makes it easier to read the existing guide.

## Tasks

- [ ] Create a `CONTRIBUTING_ID.md` file.
- [ ] Move all the Indonesian language content of `CONTRIBUTING.md` file to the newly-created file.

**Comment by resir014** [comment]
Issues + tasks list updated.

**Comment by fncolon** [comment]
> Issues + tasks list updated.

Thanks! 👍🏻
