### ISSUE TITLE
Website 2.0

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#321]
## Overview

We are revamping our website look and feel based on the new UI design reflected in this Figma file:

https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=485:2485

### Home page

- [x] #332
- [x] #352 
- [x] #333
- [x] #322
- [x] #323
- [x] #324
- [x] #504
- [x] #598 
- [x] #599 
- [x] #642
- [x] #672
- [x] #673
- [x] #668
- [x] #710

### Database-related pages

- [x] #600

### Stuff that's on a separate page

- [x] #325
- [x] #326
- [x] #327
- [x] #328
- [x] #329
- [x] #330
- [x] #712

### General structure

- [x] #346
- [x] #391
- [x] #624

### Minor tasks

- [x] #385
- [x] #422
- [x] #453

### Bugs

- [x] #448 
- [x] #498
- [x] #573
- [x] #723

**Comment by mazipan** [comment]
Can not access Figma, is it available for public?

**Comment by syauqy** [comment]
May I get permission to view the Figma link?

**Comment by zainfathoni** [comment]
> May I get permission to view the Figma link?

I'm requesting to the owners to make it publicly viewable.

In the meantime, you can start working on #322 since it already has a screenshot in the description.

**Comment by mazipan** [comment]
I think it's better to attach the screenshot on all ticket @zainfathoni

**Comment by zainfathoni** [comment]
> I think it's better to attach the screenshot on all ticket, so the developer can also know which elements/pages you mentioned on the ticket @zainfathoni 

That's the plan Mas @mazipan, I have started with #322 last night while streaming at https://zainf.dev/kerja-bakti-7 😁 

But I haven't gotten time to continue with the rest of the tickets. I'll try to do iater today.

**Comment by baraeb92** [comment]
Figma file has been updated. You should be able to see it now. @syauqy

**Comment by mazipan** [comment]
All the tickets on homepage already closed, should we remove the old markdown content on the homepage also @zainfathoni 
At least remove the section from homepage, and keep the markdown for a while.

Seems it's not available on the design.

![Screenshot_20210802-175033_Chrome](https://user-images.githubusercontent.com/7221389/127850512-3e6a2acf-f7ff-49e0-bb5d-4d95360a7350.jpg)

**Comment by zainfathoni** [comment]
Let me discuss it first with Mas @ardiwilda, the head of the content team.

**Comment by zainfathoni** [comment]
At #552, Mas @ardiwilda just removed the unnecessary sections on the home page.

However, for the remaining sections, we still need them out there until we implement #327, #328, and #329 pages and integrate them with Netlify CMS properly.

## Reference

[Slack thread link](https://kawalcovid19.slack.com/archives/C029KS7SWSJ/p1627962580004600?thread_ts=1627960941.002400&cid=C029KS7SWSJ)

<img width="1131" alt="Screenshot 2021-08-03 at 11 57 26" src="https://user-images.githubusercontent.com/6315466/127955534-2d806402-e7c1-49ed-ad57-19f857338479.png">

**Comment by resir014** [comment]
@zainfathoni What I think we can do do now is to remove the "last updated" alert, since we already have those in the Informasi Terbaru section. What do you think about that?

**Comment by zainfathoni** [comment]
> @zainfathoni What I think we can do do now is to remove the "last updated" alert, since we already have those in the Informasi Terbaru section. What do you think about that?

I'm still checking it out with Mas @ardiwilda.

**Comment by zainfathoni** [comment]
Let's remove the "last updated" alert on the home page.
[I have gotten the confirmation](https://kawalcovid19.slack.com/archives/C029KS7SWSJ/p1628473595000100?thread_ts=1628417748.001400&cid=C029KS7SWSJ) that we don't need the "last updated" alert anymore.

<img width="469" alt="Screenshot 2021-08-09 at 10 17 58" src="https://user-images.githubusercontent.com/6315466/128654291-c0015e27-ce49-4e36-a6e3-0115ad922a1b.png">

**Comment by mazipan** [comment]
![Screen Shot 2021-08-09 at 09 33 03](https://user-images.githubusercontent.com/7221389/128654996-81e103d4-c6fd-40f7-8d9e-53ce0239c211.png)

How about remove this one also @zainfathoni?

**Comment by zainfathoni** [comment]
I just notified Mas @ardiwilda that we have implemented that page and he will remove the section ASAP.
Thanks for noticing it, Mas @mazipan!

**Comment by mazipan** [comment]
We miss to create ticket for "Konseling Page" @zainfathoni 

Google Sheet: https://docs.google.com/spreadsheets/d/1JRlBNwmqoVimwR70dwIVJ1QAnBbC0Mqp0DmomeO0cWU/edit#gid=0

**Comment by resir014** [comment]
> Let's remove the "last updated" alert on the home page.
> I have gotten the confirmation that we don't need the "last updated" alert anymore.

Alright, let's create a new issue for this. @zainfathoni

**Comment by zainfathoni** [comment]
> Alright, let's create a new issue for this. @zainfathoni 

I have created the issue at #598 and I think it has been closed. 😁🚀

**Comment by mazipan** [comment]
We can remove this part from Homepage @zainfathoni.
The new page already merged

![Uploading Screen Shot 2021-08-10 at 16.25.20.png…]()

**Comment by zainfathoni** [comment]
> We miss creating ticket for the "Konseling Page" @zainfathoni
> 
> Google Sheet: https://docs.google.com/spreadsheets/d/1JRlBNwmqoVimwR70dwIVJ1QAnBbC0Mqp0DmomeO0cWU/edit#gid=0

I saw issue #668 has been created by @reinhart1010. In the meantime, [I'm checking the UI design](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1628819593022900) with Mas @baraeb92 and Mas Momo in Slack.
<img width="506" alt="Screenshot 2021-08-13 at 09 55 54" src="https://user-images.githubusercontent.com/6315466/129294007-1217f4d2-e9a7-4636-910e-ebcc1cbcd2d7.png">

**Comment by mazipan** [comment]
![Screen Shot 2021-08-13 at 09 02 22](https://user-images.githubusercontent.com/7221389/129294543-a2fa838f-1b1b-4516-b976-8b443f7c78f0.png)

We have this on Figma, but no ticket for that design.
Also it's not contains info related Apps supported by Kemenkes
