### ISSUE TITLE
Welcome Message

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#322]
## UI Design

![M01 - Modal Information](https://user-images.githubusercontent.com/6315466/126641966-f7b5996c-bf4b-4006-b304-936d3a4572fe.png)

## Implementation Model

- Only show it for the first time
- Use Local Storage to keep track of whether the modal has been shown for the first time or not
- Do not render it statically, only render it on the client side after hydration
- Make the modal editable using Netlify CMS

## Current Tasks

- [x] Create a new [Collection Type](https://www.netlifycms.org/docs/collection-types/) in Netlify CMS
- [x] Add the content to the Markdown page
- [x] Render the modal based on the Markdown page
- [x] Hide the modal by default, only show it when the user scrolls down to a certain point and the local storage value is empty
- [x] Set a value at the local storage upon closing the modal

**Comment by mazipan** [comment]
This blocker popup is not a good approach in term of web performance @resir014 @zainfathoni 

There is no way for the tools like Lighthouse to discard the popup

**Comment by zainfathoni** [comment]
I've updated the task list, Mas @mazipan, do you think it's sufficient?

**Comment by zainfathoni** [comment]
This should have been closed by #437, shouldn't it, Mas @mazipan ?

**Comment by mazipan** [comment]
I will close this, and will create another bug task if found any defects
