### ISSUE TITLE
Informasi Terbaru widget on homepage

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#324]
## UI Design

![image](https://user-images.githubusercontent.com/5663877/127315886-63d8bf76-23a8-4157-9efc-424b38878033.png)

## Implementation model

- Add category to Netlify CMS, allow adding one Markdown file per news. (Use [Folder Collections](https://www.netlifycms.org/docs/collection-types/#folder-collections) for this)
- Fields:
  - source (string, required)
  - date (datetime, required)
  - link (optional)
  - linkText (optional)
  - content (markdown text)
- Only render latest 3 (or 5?) posts to prevent rendering too many content.
- [TBD]

### Main tasks

- [x] #479
- [x] #480
- [x] Initial implementation of Latest News section (dummy data, no Netlify CMS)
- [ ] Add Netlify CMS collection
- [ ] Potentially modify tests after Netlify CMS collection addition

### Bugs

- [x] #521

**Comment by resir014** [comment]
Issues + tasks list updated.

**Comment by resir014** [comment]
@zainfathoni I think I won't have time to convert the dummy data to Netlify CMS tonight, care to help?

The dummy data I made on #511 can be converted immediately to markdown, put them as a [Folder Collection](https://www.netlifycms.org/docs/collection-types/#folder-collections) under `_content/informasi-terbaru/<timestamp-filename>.md`

The object shape of the dummy data is also ready to convert to Markdown frontmatter.

**Comment by zainfathoni** [comment]
> @zainfathoni I think I won't have time (and energy) to convert the dummy data to Netlify CMS tonight, care to help?
> 
> 
> 
> The dummy data I made on #511 can be converted immediately to markdown, put them as a [Folder Collection](https://www.netlifycms.org/docs/collection-types/#folder-collections) under `_content/informasi-terbaru/<timestamp-filename>.md`
> 
> 
> 
> The object shape of the dummy data is also ready to convert to Markdown frontmatter.

Got it, I'm working on it at #537. 👌
