### ISSUE TITLE
Edukasi page (multiple items + sub-items)

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#327]
![Screen Shot 2021-08-09 at 14 08 26](https://user-images.githubusercontent.com/7221389/128670697-e6530a08-09d0-4c76-923f-c17b4c35a803.png)

Figma: https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=458%3A2632

To Replace 

![Screen Shot 2021-08-09 at 14 09 16](https://user-images.githubusercontent.com/7221389/128670774-bb7b3a33-bc5c-4980-9cd8-82ac77c9dd92.png)

**Comment by iamyuu** [comment]
Where can I get the items and sub-items?

**Comment by mazipan** [comment]
For the UI, I suggest to wait the #628
