### ISSUE TITLE
Set up new image CDN service for static assets

### ISSUE THREAD

**Issue by ekafyi** [kawalcovid19/wargabantuwarga.com#338]
## Overview

Set up a new image CDN service to host and serve static image assets (eg. banner images).

Based on Slack conversation, the two service contenders are [Imgix](https://dashboard.imgix.com) and [Cloudinary](https://cloudinary.com). Both provide free tiers and have comparable image processing features such as compression and resize. The major difference is that _Cloudinary provides image hosting_ while Imgix requires us to add and configure our own hosting.

Shall we go with Cloudinary for the sake of simplicity (fewer accounts to configure)?

Further info on how Cloudinary quota: https://support.cloudinary.com/hc/en-us/articles/203125631-How-does-Cloudinary-count-my-plan-s-quotas-and-what-does-every-quota-mean-

### Essential

- [x] #339
- [x] #340
- [x] #341 

### Enhancements

- [x] #395

### Documentation

- [x] Document how to upload image to Cloudinary, do and donts — https://gist.github.com/ekafyi/1a86987c111a96976309c12f047d43a9
- [ ] #569

**Comment by mazipan** [comment]
+1 for using Cloudinary from me

**Comment by zainfathoni** [comment]
Since most of the tasks are completed already, I'm closing this issue so we can wrap up the [Website 2.0 milestone](https://github.com/kawalcovid19/wargabantuwarga.com/milestone/4).

The remaining issue, #569, can still be tracked under #99.
