### ISSUE TITLE
Make WBW Cloudinary account and share credentials with relevant stakeholders

### ISSUE THREAD

**Issue by ekafyi** [kawalcovid19/wargabantuwarga.com#339]
Once we agree to use Cloudinary to serve static images, a free account under WBW name and email should be created and the credentials shared to those in charge of uploading image assets.

Then #340 can be updated with the account name.

Can anyone in @kawalcovid19/wbw create the Cloudinary account and drop the username here?

**Comment by zainfathoni** [comment]
Account created, credentials will be disbursed through private channels on a need-basis.
