### ISSUE TITLE
Move the `Buka Peta` button under `Salin` button

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#344]
For the first iteration, I think #317 changes are still acceptable.
However, we should make it more consistent by putting it under the `Salin` button, so all action buttons are located on the right side.

__Originally posted by @zainfathoni in https://github.com/kawalcovid19/wargabantuwarga.com/pull/317#discussion_r675239846__

**Comment by mazipan** [comment]
The correct way is, contact some ux folks.
As them to do full revisit this page.
Then we can have a better information structure.

A micro improvement like this can be a double-job when we know the UI is still not on the best part.

I suggest to also align with UX team.

So this ticket can be picked, but we have a better vision to make this page better.

@zainfathoni

**Comment by andriawan** [comment]
I'm inline with mas @mazipan . For better decision, we need discuss at least with person with more professional in UX

**Comment by mazipan** [comment]
But this ticket can be picked as a micro improvement for any contributor that wanna working on the `good first issue` ticket.

Let's create a ticket/epic and set a priority when we can focus to do revisit this page.

**Comment by resir014** [comment]
@mazipan We can include any UX overhauls on the #110 epic. For now, we can go forward with this micro-improvement.
