### ISSUE TITLE
Improve Province Page Search Input

### ISSUE THREAD

**Issue by fncolon** [kawalcovid19/wargabantuwarga.com#347]
## Description

The user may not know that he/she can search by address, provider, description and ofcourse the contact number, then look for it by the contact number only.

![Capture](https://user-images.githubusercontent.com/50759463/126735865-d982d543-9734-4d27-bd4f-488a9848857a.PNG)

## Tasks

- [ ] Adding a placeholder to the input with text "Cari berdasarkan kontak, alamat, provider, dan keterangan"

**Comment by resir014** [comment]
Added this as a subtask to #244.

**Comment by zainfathoni** [comment]
@all-contributors please add @fncolon for ideas.
