### ISSUE TITLE
Province Search Bug on Letter A

### ISSUE THREAD

**Issue by fncolon** [kawalcovid19/wargabantuwarga.com#362]
## Description

First letter was working in search function except 'A' letter

## Expected Behaviour

A must show Aceh in the result.

## Additional Information

Link to reproduce 
1. [A](https://www.wargabantuwarga.com/provinces?q=A)
2. [a](https://www.wargabantuwarga.com/provinces?q=a)

## Tasks 

- [ ] A Letter show Aceh as the result

**Comment by ekamuktia** [comment]
The issue is related to this https://github.com/olivernn/lunr.js/issues/233

**Comment by fncolon** [comment]
> The issue is related to this [olivernn/lunr.js#233](https://github.com/olivernn/lunr.js/issues/233)

because those search was not in English, maybe we need to remove the stop word filter.

**Comment by ekamuktia** [comment]
@fncolon 
Fortunately itemsjs has this option on the configuration so it can easily done. Updated it on new pull request. 
Thanks for the report

**Comment by fncolon** [comment]
> @fncolon
> Fortunately itemsjs has this option on the configuration so it can easily done. Updated it on new pull request.
> Thanks for the report

Thanks for the responsibility 🙏
