### ISSUE TITLE
Implement an adequate styling for the Netlify CMS-managed home page

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#38]
## Tasks

- [x] #114
- [x] #190

**Comment by emer7** [comment]
Halo, issue ini maksudnya apa ya mas? Permisi kontribusi apabila boleh

_Hello, what is this issue about? Would like to try to contribute if possible_

**Comment by zainfathoni** [comment]
Thanks, @emer7 !

Please create a draft PR to signal the other contributors that you have started working on it, just like what @resir014 did in #91.

FYI, the page to be styled is already implemented in the [/home-page](pages/home-page.tsx) path.

**Comment by resir014** [comment]
Added #114 to the task list since it's somewhat linked to this issue as well.
