### ISSUE TITLE
Write some e2e tests for `Provinces` page to avoid regressions

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#381]

**Comment by aditya-setyadi** [comment]
@zainfathoni What is the goal of this issue? I see there are codes to test the province page.
Are you saying it suppose to test e2e path province/ProvinceName?

**Comment by zainfathoni** [comment]
> @zainfathoni What is the goal of this issue? I see there are codes to test the province page.
> 
> Are you saying it suppose to test e2e path province/ProvinceName?

Exactly. We need to add more e2e tests for the deeper scenarios where the users visit the `Province` page at `/provinces/[provinceSlug]` route.
