### ISSUE TITLE
Google Tag Manager is not triggered in the new homepage

### ISSUE THREAD

**Issue by baraeb92** [kawalcovid19/wargabantuwarga.com#419]
## Description

Previous Google Tag Manager is no longer triggered in Warga Bantu Warga website after the homepage revamps, thus creating an issue where data is not sent to Google Analytics. 

## Expected Behaviour

Google Tag Manager should be triggered on every page, see the previous PR here: https://github.com/kawalcovid19/wargabantuwarga.com/pull/36

## Additional Information

- [x] Add the GTM trigger back to WBW
- [x] Add proper noscript implementation for Google Tag Manager in WBW
- [ ] Add unit test to this critical functionality to ensure that future refactor will be less likely to produce the same bug, or later engineers will notice if this bug is recurring. Perhaps using React Test Library or Enzyme #425

See the discussion thread here: <img width="685" alt="Screen Shot 2021-07-25 at 22 31 49" src="https://user-images.githubusercontent.com/23743497/126904654-3a7c1fe0-2064-4ebb-b65d-676b3d8694e3.png">

**Comment by mazipan** [comment]
This need to be prioritized @zainfathoni.
Please increase the priority to be higher

**Comment by baraeb92** [comment]
Reopening this, to investigate the cause on why the noscript is not present on the <body> when the web is loaded. 

See my comment here: https://github.com/kawalcovid19/wargabantuwarga.com/pull/423/files/fd7d2157452ee2df2515a30d3d7c9494fc618f18#r676263160

**Comment by mazipan** [comment]
![Screen Shot 2021-07-26 at 10 50 41](https://user-images.githubusercontent.com/7221389/126930941-f546f6a2-23ae-4b0e-9cb5-a89fbe82cc12.png)

**Comment by mazipan** [comment]
We have issue #439

**Comment by mazipan** [comment]
Can we close this @baraeb92?

**Comment by baraeb92** [comment]
Yes we can @mazipan
