### ISSUE TITLE
[UX] Bottom Page Navigation Improvements

### ISSUE THREAD

**Issue by fncolon** [kawalcovid19/wargabantuwarga.com#422]
## Description

there are several things that interfere with the bottom page navigation, including the location of the navigation items that are different from the previous version, and the use of mixed language.

![126778941-3cee2218-fb7a-4cff-94a0-412b84f25d8e](https://user-images.githubusercontent.com/50759463/126905844-9ef5c9d4-0fe4-4327-9391-20acf5f600ef.png)

`Pusat Data` used more often, but is in third place.

![Capture](https://user-images.githubusercontent.com/50759463/126905861-560e6a75-3e2d-4b2d-a19e-75751b7d6ccd.PNG)

## Tasks

- [ ] Reorder navigation items according to the updated Figma file
- [ ] Rename menu items according to the updated Figma file.

**Comment by baraeb92** [comment]
The feedback has been included in our latest design changes and will be part of the work on website 2.0 

See the latest design proposal here: https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=485%3A2485

@zainfathoni
