### ISSUE TITLE
commitizen causing error in Windows 10

### ISSUE THREAD

**Issue by ekamuktia** [kawalcovid19/wargabantuwarga.com#426]
## Description

commitizen causing error in Windows 10

> husky/prepare-commit-msg: line 4: /dev/tty: No such device or address husky - prepare-commit-msg hook exited with code 1 (error)

## Expected Behaviour

Should work in all OS

## Additional Information
related issue https://github.com/commitizen/cz-cli/issues/627

**Comment by resir014** [comment]
I'm replacing commitizen with [commitlint](https://github.com/conventional-changelog/commitlint) - it focuses more on linting the commit message and it doesn't seem to require a command which only works on non-Windows devices.
