### ISSUE TITLE
Contact page is inaccessible

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#431]
## Description

Contact Page is inaccessible

https://user-images.githubusercontent.com/6315466/126915737-66af354f-ad67-4e43-be88-5c0a1e9b07be.mov

## Expected Behaviour

Contact Page is accessible

## Additional Information

Probably due to changes in #288 ?

**Comment by mazipan** [comment]
Duplicate w #424

**Comment by mazipan** [comment]
PR on #427
