### ISSUE TITLE
Typo in some FAQ answers

### ISSUE THREAD

**Issue by mddarmawan** [kawalcovid19/wargabantuwarga.com#434]
## Description

1. selanjurnya -> selanjutnya
![Screen Shot 2021-07-26 at 08 04 56](https://user-images.githubusercontent.com/22543134/126920091-a074a334-5e15-4a38-8ede-d1ce21aa8a45.png)

2. disinfekfan -> disinfektan
![Screen Shot 2021-07-26 at 08 07 04](https://user-images.githubusercontent.com/22543134/126920146-76b8ff05-a1bd-4b4c-a75c-8a7314b566fd.png)

3. telpon -> telepon ([_source_](https://kbbi.kemdikbud.go.id/entri/telepon))
![Screen Shot 2021-07-26 at 08 09 08](https://user-images.githubusercontent.com/22543134/126920239-a69e796f-f2f1-475f-ad9c-85bad9425afd.png)

## Expected Behaviour

The typo should be fixed.

**Comment by hendraaagil** [comment]
I already requested an edit access to [FAQ COVID-19](https://docs.google.com/spreadsheets/d/1oO5ZeC_Qgo7e8s4vMDukWCGSEquefbcOFQsQU5ksxIM/) Spreadsheet to fix this typo😄

**Comment by zainfathoni** [comment]
For this type of issue, let's ask Mas @ardiwilda to take care of it. 😁

**Comment by zainfathoni** [comment]
I just updated the https://kcov.id/wbw-faq short link to point to another sheet that we own, so we can update the sheets by ourselves. It should go live in less than 30 minutes.

**Comment by zainfathoni** [comment]
I have verified that all the typos raised above have been resolved. Thanks, Mas @ardiwilda!

**Comment by zainfathoni** [comment]
@all-contributors please add @ardiwilda for content
