### ISSUE TITLE
Update Sembako image and CTA icon sizes

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#449]
[Context](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1627303498021600?thread_ts=1627300756.018400&cid=C0279E2Q99Q)

<img width="276" alt="Screenshot 2021-07-26 at 20 50 00" src="https://user-images.githubusercontent.com/6315466/126991506-148ca6e9-16ed-43b0-b7f2-a0688ca06edb.png">

**Comment by resir014** [comment]
@zainfathoni Will need a raw version of the CTA image. I'm trying to download from the Figma but it's heavily scaled down: 

![image](https://user-images.githubusercontent.com/5663877/126992484-48cab390-675d-4297-abb0-738784846d47.png)

**Comment by bungmomomm** [comment]
Here is the banner for sembako

<img width="328" alt="banner-sembako@2x-min" src="https://user-images.githubusercontent.com/30654812/126994068-12648474-f79c-4590-80e1-e9accb0ce160.png">
