### ISSUE TITLE
Trailing semicolon at the end of the homepage

### ISSUE THREAD

**Issue by zsbahtiar** [kawalcovid19/wargabantuwarga.com#464]
## Description
halo tim wargabantu warga. Saya menemukan issue yang kecil diatas menu navigasi.
<img width="736" alt="Screen Shot 2021-07-27 at 09 59 38" src="https://user-images.githubusercontent.com/8356972/127088332-3a8d80ce-2cd6-49b7-92c2-a2568d88ab4d.png">

## Expected Behaviour

<img width="736" alt="Screen Shot 2021-07-27 at 10 00 46" src="https://user-images.githubusercontent.com/8356972/127088424-13adbdaf-54f3-4660-a8b1-1be80a38d233.png">

## Additional Information
di buka pada browser:
- safari (Version 14.1.1 (16611.2.7.1.4))
- chrome (Version 92.0.4515.107)

**Comment by resir014** [comment]
Hi @zsbahtiar, there is indeed a trailing semicolon at the homepage. Removing this on #467. Thanks!
