### ISSUE TITLE
Add `security.txt` file to make it easier for security researchers to submit security vulnerability reports

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#482]
## Description

The main purpose of `security.txt` is to help make things easier for companies and security researchers when they want to get in touch with us about security issues.

The https://securitytxt.org/ website provides a generator for `security.txt` file as well as a FAQ, and the technical standard (draft) can be viewed [here](https://tools.ietf.org/html/draft-foudil-securitytxt-12).

## Implementation Model

- Generate a `security.txt` file using https://securitytxt.org/ - make sure that the email used for this text file is active *and* secure.
- Make sure to set an expiration period for the `security.txt` to be 1 year at the latest. We need to also make sure that these credentials get properly rotated when we need to renew these details.
- Place the `security.txt` file in the `.well-known` folder of our root site directory: `public/.well-known/security.txt`

## Tasks

- [ ] Generate `security.txt` file using the requirements listed above.

**Comment by apraditya** [comment]
Do we know the email / URL to use as the Contact?

**Comment by resir014** [comment]
@apraditya I don't know yet. Pinging the rest of @kawalcovid19/wbw.

**Comment by zainfathoni** [comment]
@apraditya @resir014 
Please use `admin@kawalcovid19.id` email for that. We're using the same email in our [CODE_OF_CONDUCT.md](https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/CODE_OF_CONDUCT.md#enforcement).

**Comment by zainfathoni** [comment]
@all-contributors please add @resir014 for security
