### ISSUE TITLE
Add more test assertions for the component functionalities

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#509]
The snapshot test is good for asserting the styling changes.
Nevertheless, I think it would be helpful if we add another test assertion this `href` property to signal the developers that it's something that matters in this component.

_Originally posted by @zainfathoni in https://github.com/kawalcovid19/wargabantuwarga.com/pull/506#discussion_r679630513_

**Comment by rubiagatra** [comment]
Can I help with the testing? @zainfathoni is this something like this? https://stackoverflow.com/questions/57827126/how-to-test-anchors-href-with-react-testing-library

**Comment by zainfathoni** [comment]
> Can I help with the testing? @zainfathoni is this something like this? https://stackoverflow.com/questions/57827126/how-to-test-anchors-href-with-react-testing-library

Yes, exactly. We have exactly the same implementations across our test scenarios, but they're not implemented in all of them.

Therefore, please help us to implement them, especially in the tests where we're only relying solely on the snapshots.

Thanks, @rubiagatra! 🙏
