### ISSUE TITLE
Update the WhatsApp link to indicate that it's coming from our website

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#510]
@resir014 in the last meeting we want to explore possibilities to include predefined message template when user is clicking the hotline button. 

So that we can analyze how many of the user that get in touch with us, is actually coming from the WBW website. 

So to enable that we need to modify the link used to include the template text. 

Would you mind to change all the link that directing user to Whatsapp to this link instead? 

https://api.whatsapp.com/send?phone=6281257579812&text=Halo%20hotline%20Warga%20Bantu%20Warga,%20saya%20saat%20ini%20membutuhkan%20bantuan%20terkait%20dengan%20covid-19

Cc: @mazipan @zainfathoni

_Originally posted by @baraeb92 in https://github.com/kawalcovid19/wargabantuwarga.com/issues/506#issuecomment-889610644_

**Comment by mazipan** [comment]
I think @baraeb92 already create the shortened version of the URL

**Comment by baraeb92** [comment]
Here's the short link version https://bit.ly/hotlinewarga

Probably the only url left to change is the one in navbar

**Comment by resir014** [comment]
@zainfathoni @baraeb92 This was already added with the mentioned PR:

https://github.com/kawalcovid19/wargabantuwarga.com/commit/8ad5da11cb0a9afdbc3e5bdba419d56caebaec83

Or are we talking about something else?

**Comment by baraeb92** [comment]
Have we also changed the url used in navbar and in the hamburger menu @resir014 ?

**Comment by resir014** [comment]
Oh yea, that one I haven't. @baraeb92
