### ISSUE TITLE
Sembako WBW getting Blank

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#516]
## Description

https://sembako.wargabantuwarga.com/ is getting blank page

## Expected Behaviour

Should accessible

**Comment by zainfathoni** [comment]
Apparently, the URL is updated to https://petakebaikan.kitabisa.com/
We have to update the URL from our website, then.

**Comment by mazipan** [comment]
Move to the constant, so we can update it in a single place in the future.

**Comment by zainfathoni** [comment]
The same subdomain would go live again actually but in a static page form.
But yeah, for now, we have to update the URL not to go to a blank page. 😅

**Comment by mazipan** [comment]
At least for technical part, we need to make it simpler to be updated.

- Move to single place - quick fix
- Think to move it to CMS in the future
