### ISSUE TITLE
Internal links in Isolasi Mandiri page opens in a new tab

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#535]
## Description

On the stacked links in Isolasi Mandiri page, links that are meant to be internal opens in a new tab instead of in the current one.

![image](https://user-images.githubusercontent.com/5663877/127762159-755e44e0-3f58-4ea6-86fc-9dd16f0f3f14.png)

## Expected Behaviour

Internal links (`e.g. FAQ`) should be opened in the same tab.

## Additional Information

The current implementation on `StackedLink` makes all links always open on a new tab, regardless of whether it is an external link or not. We should add a way to differentiate this, either through an extra Boolean item on the Netlify CMS page, or through a logic within the component.

**Comment by zainfathoni** [comment]
I think an internal logic is better, since we can't rely too much on the Netlify CMS restrictions.
