### ISSUE TITLE
"Sampaikan masukan" in all pages

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#545]
## Description

We already create a link in the homepage to submit any discussion if the user found the bugs from our web.

But the visibility is very bad, it's only on the homepage which is quite long to be scrolled.

![Screenshot_20210802-174859_Chrome](https://user-images.githubusercontent.com/7221389/127850752-20c23f33-672f-4f16-bdfe-472a51306574.jpg)

## Implementation Model

My suggestion is to put it in all pages.
Keep it on the very bottom, like the `copyright` in the other websites.
But need confirmation from @zainfathoni if he wants to take this or just close this if it's invalid.

## Tasks

- [ ] Create seperate React Component
- [ ] Put it on the Layout

**Comment by zainfathoni** [comment]
Agreed. I think it's better if we can make it a part of our layout that appears on every page.

Currently, we have no proper footer for the page that contains the Copyrights and other relevant information, including our GitHub repository.

**Comment by nasrulgunawan** [comment]
Hai Mas, could I work on this ticket?

*I've never worked on a React project, but I've tried web components and Tailwind, may I try (while I'm learning)?

**Comment by mazipan** [comment]
Please try to take a look the code and run on your local first, if you think you can work on this, then please take it.

**Comment by zainfathoni** [comment]
Agreed. Once you're able to set this project up locally in your machine, you can start creating a draft pull request to signal other developers that you're currently working on it.
Please read [our contributing guide](https://kcov.id/wbw-contributing) for more complete guidelines.

**Comment by nasrulgunawan** [comment]
Well noted Mas @mazipan, Mas @zainfathoni.
I will try to create a draft pull request first.
