### ISSUE TITLE
Add "buka peta" button in province list

### ISSUE THREAD

**Issue by ramarahmanda** [kawalcovid19/wargabantuwarga.com#570]
## Description

I feel that _alamat_ shortcut is inconsistent we can open map in detail but not in the list. Also it can benefit user to suitable location to fasten their search without have go to detail page

Detail
![image](https://user-images.githubusercontent.com/12446260/128432938-72928c4f-5ff8-4162-a111-c56d3e8d71c0.png)

List
![image](https://user-images.githubusercontent.com/12446260/128433022-2826a227-7ed9-4a3b-afda-f790971c65d5.png)

## Tasks

- [ ] Add `OpenMapButton` component in province list

**Comment by mazipan** [comment]
Do we want to work on this @zainfathoni?

**Comment by zainfathoni** [comment]
> Do we want to work on this @zainfathoni?

I think it's a good point to make the actions more consistent.
I'm fine with it as long as the behaviours are identical.
