### ISSUE TITLE
Incorrect copywriting on Database CTA

### ISSUE THREAD

**Issue by resir014** [kawalcovid19/wargabantuwarga.com#573]
## Description

On the Database CTA, the copywriting for the button is written as "Cek sekarang", where it should've been "Telusuri sekarang"

## Expected Behaviour

![image](https://user-images.githubusercontent.com/5663877/128456730-e69d900c-e695-4922-972d-5997716436bd.png)

**Comment by morezam** [comment]
Hi, can I work on this?

**Comment by resir014** [comment]
@morezam sure!
