### ISSUE TITLE
Font size on label filters are not same with the search label

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#583]
## Description

The font size from the labels are not consistent, the search seems have a smaller font size.

Sample page: 

https://www.wargabantuwarga.com/provinces/dki-jakarta

The size for word "Cari Kontak" is not same with "Kategori" & "Lokasi"

See screenshot:

![Screenshot_20210807-191232_Chrome](https://user-images.githubusercontent.com/7221389/128599750-e4490114-b9a2-463a-b6ba-8968364bc4f8.jpg)

## Expected Behaviour

I think we need to set smaller font size for the label in filters

**Comment by resir014** [comment]
@mazipan There's also `FormLabel` component, we should use it across all form elements.

https://github.com/kawalcovid19/wargabantuwarga.com/blob/main/components/ui/forms/form-label.tsx

**Comment by adylanrff** [comment]
Hi, can I work on this?

**Comment by adylanrff** [comment]
After looking at the code, I think both `SearchForm` and `SearchFilter` have already used the `FormLabel` component for the label.

**Comment by adylanrff** [comment]
Hi @mazipan need your input here, since the font size is actually already the same, is this issue still relevant?

**Comment by mazipan** [comment]
Wdyt?

![Screenshot_20210808-205732_Chrome](https://user-images.githubusercontent.com/7221389/128634502-6d582b97-a2e2-4ff2-8282-0cff7edf174b.jpg)

**Comment by adylanrff** [comment]
Yeah that looks different ya, 

For a comparison
IPhone 12 mini (IOS 14.7.1) using Safari

![image](https://user-images.githubusercontent.com/19769774/128634915-0724be28-74f7-452e-98dc-fdb86fe7d4c9.jpeg)

**Comment by mazipan** [comment]
Arghhh, it's hard.
A spesific browser/device issue 😤

**Comment by bungandy** [comment]
Iya mas @mazipan they are fine on Chrome iOS 14 iPhone 7. Try to change the word Cari kontak -> Cari Kontak maybe? The small k character makes the word looks smaller then the other to me 😁

**Comment by adylanrff** [comment]
yeah @bungandy I thought so too, but changing `Cari kontak` --> `Cari Kontak` means changing other components that uses `SearchForm` component too, which may not be intended.

**Comment by mazipan** [comment]
It should keep to use "Cari kontak".
I will close this issue for now ya 🙏
