### ISSUE TITLE
The Footer Navigation Overlaps The Tab Bar in Safari 15

### ISSUE THREAD

**Issue by hanihusam** [kawalcovid19/wargabantuwarga.com#590]
## Description

When the user scrolls the page, the footer navigation overlaps the tab bar in Safari 15.

Default
![Default](https://user-images.githubusercontent.com/25399426/128636444-64012ee9-59e1-4e2f-984f-ef1eb02c800c.jpeg)

User Scrolls
![photo_2021-08-08 21 57 44](https://user-images.githubusercontent.com/25399426/128636512-310a62b6-4dce-47d9-91a8-5633c124afe8.jpeg)

#FYI Safari 15 has new features/looks which one of them is focusing the browser on the website content. I think we need update a few codes (a little) to handle the new behavior. Here is the [reference](https://developer.apple.com/videos/play/wwdc2021/10029/) about Safari 15.

## Expected Behaviour

The navigation footer should in the top of the tab bar either in the default situation or when the user scrolling the page.

## Additional Information

We can use safe area insets to move the footer navigation up by the appropriate amount. We need to put this line `env(safe-area-inset-bottom)` in the padding/margin bottom value.

**Comment by resir014** [comment]
Unfortunately Tailwind doesn't support `env(safe-area-inset-bottom)` yet. Until then, there's nothing we can do about it, unless we add a `@layer components` rule with a helper class which adds this.

**Comment by hanihusam** [comment]
Due to Apple has fixed this issue, I will close this issue.
