### ISSUE TITLE
Typo in the word "hinggu" which should be "hingga"

### ISSUE THREAD

**Issue by Widi-ps** [kawalcovid19/wargabantuwarga.com#591]
[
![Screenshot_2021-08-08-22-57-23-82](https://user-images.githubusercontent.com/69189062/128638547-6e0ccd84-631f-422f-adcc-6177eba6a064.png)
](url)

**Comment by krisnafirdaus** [comment]
<img width="610" alt="Screen Shot 2021-08-08 at 23 55 29" src="https://user-images.githubusercontent.com/67870639/128639505-a4096200-6d92-419f-a840-c19cca4ffe77.png">
like this ?

**Comment by Widi-ps** [comment]
yup, maybe you can pull it out? because I see in the browser is still the same
![image](https://user-images.githubusercontent.com/69189062/128639720-a976f845-c26e-4329-928e-9558bb7399f4.png)

**Comment by krisnafirdaus** [comment]
in this file have ignore when i push code. please let me know how to push code ? @zainfathoni

**Comment by zainfathoni** [comment]
It's only editable from our [Google Spreadsheets file](https://kcov.id/faq-sheets). I'll let Mas @ardiwilda know, he manages our data on the spreadsheets.

**Comment by zainfathoni** [comment]
<img width="591" alt="Screenshot 2021-08-09 at 10 08 32" src="https://user-images.githubusercontent.com/6315466/128653908-75dbdb41-106b-4dba-8860-39b002d03a92.png">

The typo has been fixed. Thanks, @Widi-ps for reporting the issue. 🙏

**Comment by zainfathoni** [comment]
@all-contributors please add @Widi-ps for bug.
