### ISSUE TITLE
Remove the "last updated" alert on the home page

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#598]
Let's remove the "last updated" alert on the home page.
[I have gotten the confirmation](https://kawalcovid19.slack.com/archives/C029KS7SWSJ/p1628473595000100?thread_ts=1628417748.001400&cid=C029KS7SWSJ) that we don't need the "last updated" alert anymore.

<img width="469" alt="Screenshot 2021-08-09 at 10 17 58" src="https://user-images.githubusercontent.com/6315466/128654291-c0015e27-ce49-4e36-a6e3-0115ad922a1b.png">

_Originally posted by @zainfathoni in https://github.com/kawalcovid19/wargabantuwarga.com/issues/321#issuecomment-894912512_

## Acceptance Criteria

- [x] Remove the component rendering from the home page
- [x] Remove the widget from Netlify CMS
- [x] ~Update the failing tests accordingly~

**Comment by antoooks** [comment]
Hi mas @zainfathoni can I take this one?

**Comment by mazipan** [comment]
As usual, create a draft PR to tell all contributors that someone already working on this issue

**Comment by zainfathoni** [comment]
This issue is not done yet because the last PR reduced the home page's code coverage unnecessarily.

https://github.com/kawalcovid19/wargabantuwarga.com/pull/604#pullrequestreview-725197608

**Comment by antoooks** [comment]
> This issue is not done yet because the PR #604 [reduced the home page's code coverage unnecessarily](https://app.codecov.io/gh/kawalcovid19/wargabantuwarga.com/compare/604/diff#diff-cGFnZXMvaW5kZXgudHN4).
> 
> We need to restore the test scenarios that are still relevant for the page.
> 
> [#604 (review)](https://github.com/kawalcovid19/wargabantuwarga.com/pull/604#pullrequestreview-725197608)

I can fix it. So I have to make sure if the said component is not rendered?

**Comment by zainfathoni** [comment]
> I can fix it.

While you're at it, please also fix the way we're querying and asserting the components, as I have explained in https://github.com/kawalcovid19/wargabantuwarga.com/pull/604#pullrequestreview-725215702.

Thanks, @antoooks! 🙏

**Comment by zainfathoni** [comment]
I'm reopening this issue since [many testing assertion issues](https://github.com/kawalcovid19/wargabantuwarga.com/pull/614#pullrequestreview-729223117) still need to be addressed.

**Comment by rubiagatra** [comment]
Will take a look this weekend @zainfathoni , to list assertion issues

**Comment by zainfathoni** [comment]
> Will take a look this weekend @zainfathoni, to list assertion issues

Would you please collect all the testing practices across the project that we need to refactor and put them under this #688 epic, Mas @rubiagatra? I have invited you as a collaborator into the project, so you should be able to edit the epic's description once you accepted my invitation.
Thanks! 🙏

**Comment by rubiagatra** [comment]
Sure!, I already accepted invitation, thanks mas @zainfathoni will do my best
