### ISSUE TITLE
Some Long Address Overflow

### ISSUE THREAD

**Issue by maziyank** [kawalcovid19/wargabantuwarga.com#613]
## Description

Very long address should not be overflow like this.
Two close **salin** button made me confusing. Suppose to be different.

![wargabantuwarga2](https://user-images.githubusercontent.com/3317904/128692882-a814a904-cb2d-4e60-a77a-5ee1a7fd0149.gif)

## Tasks

- [ ] (fix adress overflow)
- [ ] (improve close salin button)

**Comment by fadillicious** [comment]
Hi mas @maziyank and @zainfathoni, I'm new in this project but I interest to contribute.

## Problem
I found problem address overfrow from source data `~/data/wbw-sheets.json`, in address string have tag html

<img width="955" alt="Screen Shot 2021-08-10 at 08 33 12" src="https://user-images.githubusercontent.com/10627998/128796579-9d279460-1b49-4aad-bdc6-dc4cacd682e2.png">

<img width="721" alt="Screen Shot 2021-08-10 at 08 10 29" src="https://user-images.githubusercontent.com/10627998/128796598-5dbb0c06-47d4-4471-8cc2-428c6adb6c43.png">

<img width="694" alt="Screen Shot 2021-08-10 at 08 09 51" src="https://user-images.githubusercontent.com/10627998/128796616-41f4b9ec-4dd0-4bf4-9f25-4196d435456f.png">


## Solution
I try add `stripTags` method from `~/lib/string-utils`

<img width="687" alt="Screen Shot 2021-08-10 at 08 49 51" src="https://user-images.githubusercontent.com/10627998/128796728-c9be40ed-754d-456f-88c1-643211dc674e.png">

<img width="646" alt="Screen Shot 2021-08-10 at 08 49 04" src="https://user-images.githubusercontent.com/10627998/128796742-36abb900-30e3-470b-8036-1c2f939449eb.png">


how about this solution?

**Comment by maziyank** [comment]
That make sense @fadillicious.
But instead of calling same function `stripTags(contact.alamat)` 3 times, any other way to make it more efficient?

**Comment by fadillicious** [comment]
> That make sense @fadillicious.
> 
> but i am confusing since `stripTags(contact.alamat)` will remove all html tags, it leave only text. Right? Is still it necessary to passed to htmr function for rendering?
> 
> Also, instead of calling same function `stripTags(contact.alamat)` 3 times, i thinking about to make it more efficient.

Thank mas @maziyank for your response.

htmr function from existing code, in this case I only add `stripTags`.

Based on your input, maybe I can change code like this?

1. I create `contactAddress` variable with stripTags
<img width="781" alt="Screen Shot 2021-08-10 at 10 58 54" src="https://user-images.githubusercontent.com/10627998/128806265-10291fc2-7268-427d-a327-ff52b8e3f86f.png">

2. then I call the variable
<img width="828" alt="Screen Shot 2021-08-10 at 10 58 40" src="https://user-images.githubusercontent.com/10627998/128806275-6bd9fbf2-a12b-4aeb-9a3e-f48ba0e97bb6.png">

**Comment by zainfathoni** [comment]
> Also, instead of calling same function stripTags(contact.alamat) 3 times, i thinking about to make it more efficient.

We can do it by applying the `stripTags` in the upstream process, which is fetching the data in `fetch-sheets.ts`. To be more specific, I think it should be done in the [contactReducer](https://github.com/kawalcovid19/wargabantuwarga.com/blob/983972edceec8b7af2eb1807e35ab4cf9ca18f9e/etc/fetchers/utils.ts#L54-L79) function here.

**Comment by fadillicious** [comment]
thank mas @zainfathoni for your suggestion, I have submit PR 🙏

**Comment by zainfathoni** [comment]
@all-contributors please add @maziyank for bug
