### ISSUE TITLE
Implement FAQ Page

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#64]
## Description

Currently, one of the links on our website links to an [FAQ Google Sheets](https://kcov.id/wbw-faq).

We need to provide an easy way to consume its content.

## Implementation Model

The Google Sheets fetcher has been implemented on #33 by @adityapurwa. We can use the same method to fetch this https://kcov.id/wbw-faq Google Sheets.

## Tasks

- [x] #65
- [x] #66

**Comment by andriawan** [comment]
let me handle this @zainfathoni

**Comment by andriawan** [comment]
is there any specific UI design for this page @zainfathoni ?

**Comment by zainfathoni** [comment]
Please try to implement Tailwind UI's responsive design for this, as I am planning to do in #75.

If you need any help for it, you can message me privately. 😉

**Comment by ekamuktia** [comment]
The result from faq sheet fetcher remove new line on the content, so jawaban part doesn't show properly
Let me fix this @zainfathoni
