### ISSUE TITLE
Install ImgBot App

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#640]
## Description

We can auto compress all images in the repository with ImgBot.

## Tasks

- [x] Install GH App [ImgBot](https://github.com/marketplace/imgbot/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4xNzQ5#pricing-and-setup)
- [x] Allow for WargaBantuWarga repo (feel free to give access to all repo)

**Comment by fauzialz** [comment]
Is this issue can only be closed by someone who has direct access to the kawalCovid19 account/repos?

**Comment by mazipan** [comment]
Only for the owner of this organisation

**Comment by zainfathoni** [comment]
Done. How can we verify that it's working, Mas @mazipan? 😁

**Comment by zainfathoni** [comment]
Oh, there it is! #693 🚀
