### ISSUE TITLE
Need to fix typo and options in province location

### ISSUE THREAD

**Issue by maziyank** [kawalcovid19/wargabantuwarga.com#648]
## Overview

The location seems to inconsistent and there a typo (Jakrta Timur and Jakarta Barat).

## Current Tasks

- [ ] Fix Location Typo and Consistency

![jakarta wbw](https://user-images.githubusercontent.com/3317904/129126086-6cacf911-cddd-4e4b-96cd-79c6d775e066.gif)

**Comment by dekwahdimas** [comment]
If we want to fix this issue, it needs to be done from Google Docs, right?

**Comment by zainfathoni** [comment]
Yes, it is. I have notified the content editor to fix it.
Thanks for the report, Mas @maziyank"
