### ISSUE TITLE
Explore a better font loading mechanism

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#664]
## Description

One of our problematic loading in initial load is our `Inter Font`

![Screen Shot 2021-08-12 at 21 41 04](https://user-images.githubusercontent.com/7221389/129216964-89aa8ecb-0e6b-4761-bb79-a483ee4934b5.png)

There are several things need to tackle:

1. Since font are rarely change, should we treat as static file without `hashing`? Hashing will remove the cache in every deployment.
2. Find a way how to preload this request, since it will be used immediately so we need to preload the request.

## Tasks

- [ ] ...
- [ ] ...
- [ ] ...

**Comment by svspicious** [comment]
I can work on this.

My solution is to replace `typeface-inter` with self-hosted font (yes as a static file) and then `Cache-Control` via `netlify.toml`

also we can use **Inter** *variable fonts* used by vercel here (https://vercel.com/design/text) it's smaller only 38kb
https://assets.vercel.com/raw/upload/v1587415301/fonts/2/inter-var-latin.woff2
![image](https://user-images.githubusercontent.com/35674157/129310261-3e15c6b9-2a2f-4f55-862d-eca97af05fe0.png)

compared to what we use now
![image](https://user-images.githubusercontent.com/35674157/129310189-470a4dce-7d8c-4ec0-ab0b-63002d55585e.png)

reff:

- https://github.com/leerob/leerob.io/pull/260

**Comment by zainfathoni** [comment]
Nice, sounds good. Please proceed with this approach, @svspicious. Create a [draft pull request](https://kcov.id/draft-pr) and add a `need-perf-check` label on the PR to trigger the Lighthouse CI check on the changes and see its impact on the performance.

**Comment by svspicious** [comment]
Can you help me to add the label mas @zainfathoni ?

**Comment by zainfathoni** [comment]
> Can you help me to add the label mas @zainfathoni ?

Done. Let's wait for [the result](https://github.com/kawalcovid19/wargabantuwarga.com/pull/694/checks?check_run_id=3319509306) now.
