### ISSUE TITLE
Improve and organize the list of telemedicine apps in the homepage

### ISSUE THREAD

**Issue by reinhart1010** [kawalcovid19/wargabantuwarga.com#668]
## Description

I just got a recent update from the designer that the new design for this section is ready.
Based on the design, we should keep it on the home page.

[Figma link](https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=472%3A2939)

<img width="905" alt="Screenshot 2021-08-13 at 19 53 58" src="https://user-images.githubusercontent.com/6315466/129353376-47ba728a-5d9c-49bc-bdcb-684a123272b6.png">

## Implementation Model

- [ ] Build the component
- [ ] Source the content from a hardcoded JSON constant
- [ ] Implement Netlify CMS integration

## Original Post

Yeah, I mean this exact list of links:

![image](https://user-images.githubusercontent.com/17312341/129222478-7fed475a-d3ea-4a67-bea0-58a70cbc63e2.png)

There's a very few distinctions between one hyperlink and another, making the list of links a little bit confusing for some user. Since the content is originally served in Markdown (and Markdown doesn't officially support horizontal columns similar to those in *Microsoft Word*) I'm recommending splitting it into a three-column table of links like this:

**Download aplikasi telemedicine yang didukung Kemenkes:**

| [Alodokter](https://bit.ly/alodokter-isoman) | [GetWell](https://play.google.com/store/apps/details?id=id.paquesid.getwell) | [Good Doctor](https://gooddoctor.onelink.me/Cmiw/efeba7ae) |
|:-:|:-:|:-:|
| **[GrabHealth](https://grab.onelink.me/2695613898/fe73b8c5)** | **[Halodoc](https://bit.ly/isoman_halodoc)** | **[KlikDokter](https://bit.ly/kd-kemenkes-isoman)** |
| **[KlinikGo](https://klinikgo.com/isoman)** | **[Link Sehat](https://link.linksehat.com/mRMf)** | **[Milvik Dokter](https://milvik.id/about-us/)** |
| **[ProSehat](https://prosehat.com/wa)** | **[SehatQ](https://sehatqapp.onelink.me/bgzy?pid=kemenkes&c=sqkemenkes&deep_link_value=https%3A%2F%2Fwww.sehatq.com%2Ftelemed&af_web_dp=https%3A%2F%2Fwww.sehatq.com%2Ftelemed&af_dp=https%3A%2F%2Fwww.sehatq.com%2Ftelemed)** | **[YesDok](https://bit.ly/ISOMAN-YesDok)** |

I believe fixing this issue could be easy and trivial (just to make sure that the generated table is responsive), so I'd recommend for this issue to fall into `Good First Issue`.

**Comment by mazipan** [comment]
Actually the content is coming from CMS, we are in progress moving all part to the new page as mentioned on #321

**Comment by zainfathoni** [comment]
Based on [the discussion on Slack](https://kawalcovid19.slack.com/archives/C0279E2Q99Q/p1628819593022900).
We can move the description to the top of the [Telemedicine](https://www.wargabantuwarga.com/telemedicine) page.

<img width="406" alt="Screenshot 2021-08-13 at 11 19 42" src="https://user-images.githubusercontent.com/6315466/129300295-351f0944-d3d8-4a3d-baaa-c97a71e13a19.png">

**Comment by mazipan** [comment]
Even if we want to develop a proper UI, I think it also not a hard actually, it's not a tricky ticket.
But yeah, just move to CMS for now.

**Comment by zainfathoni** [comment]
I just got a recent update from the designer that the new design for this section is ready.
Based on the design, we should keep it at the home page.

[Figma link](https://www.figma.com/file/XNNtIoFEdFqaXOee83n0oN/WBW?node-id=472%3A2939)

<img width="905" alt="Screenshot 2021-08-13 at 19 53 58" src="https://user-images.githubusercontent.com/6315466/129353376-47ba728a-5d9c-49bc-bdcb-684a123272b6.png">

**Comment by mazipan** [comment]
What about entry point for "Konseling page" mas @zainfathoni?

**Comment by resir014** [comment]
@mazipan Let's put that in another issue.

**Comment by dekwahdimas** [comment]
I saw this page is already launched. Can we close this issue?
