### ISSUE TITLE
Remove educations section from homepage

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#673]
## Description

Part of #327, we need to remove the section on we merge the PR

## Tasks

- [ ] Update from CMS

**Comment by zainfathoni** [comment]
Where can we navigate to the Education section from the home page, Mas @mazipan?

**Comment by mazipan** [comment]
On #674, waiting for next cronjob for deployment

**Comment by mazipan** [comment]
![Screen Shot 2021-08-13 at 11 35 06](https://user-images.githubusercontent.com/7221389/129305385-78c57f94-84e7-47b9-8d57-e7a9c1b897c8.png)

It's already LIVE
