### ISSUE TITLE
Fix warnings in `Tentang Kami` page test

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#717]
## Description

Run this test

```shell
yarn test tentang-kami
```

And you'll see a lot of warnings due to the absence of `width` property in the `next/image` usages.

<img width="600" alt="Screenshot 2021-08-14 at 09 44 21" src="https://user-images.githubusercontent.com/6315466/129430803-81ebb704-856c-443a-92ca-6e5b65745c58.png">

## Expected Behaviour

No warnings should be shown

**Comment by zainfathoni** [comment]
Probably the simplest way of fixing this issue is by adding a proper `width` props to the Image component.
What do you think, @resir014 & @ekafyi?

**Comment by ekafyi** [comment]
> Probably the simplest way of fixing this issue is by adding proper `width` props to the Image component.
> What do you think, @resir014 & @ekafyi?

Yes, Next's Image component is supposed to have a width prop, like in Home page banners.

**Comment by resir014** [comment]
Closed in #734.
