### ISSUE TITLE
Update CONTRIBUTING.md to educate about disable forked repo actions

### ISSUE THREAD

**Issue by ryanadhi** [kawalcovid19/wargabantuwarga.com#736]
## Description

I got these constant notification from forked repo that the GitHub actions is failed, which I believe run every 30mins
![Screenshot 2021-08-15 110557](https://user-images.githubusercontent.com/35433920/129466903-5a4eefb2-a9dc-4c0b-9084-55c20ac1715d.png)

## Additional Information

reproduce steps

1. forked repo
2. occasionally fetch new commits from original repo
3. GitHub action runs and fail

is it something that expected to happen? or is there something that I did it wrong? 
Thanks

## TODO: Task
- [ ] #736 
- [x] #740

**Comment by zainfathoni** [comment]
It's expected, since you don't provide sufficient GitHub Action secrets (a.k.a. Environment Variables) to your forked repository.

The simplest solution is by disabling GitHub Actions on your forked repository.
The more complex solution (which I don't think is necessary) is to provide the environment variables for your own instances, such as Netlify, Lighthouse CI, Codecov, Cypress Dashboard, etc.

**Comment by zainfathoni** [comment]
To spread this information to the rest of the contributors, would you please make some changes to our CONTRIBUTING.md file to explain this situation? 😁
Thanks! 🙏

**Comment by rubiagatra** [comment]
maybe we can use this kind of solution @zainfathoni ? 🤔  https://github.com/arduino/arduino-cli/pull/888/files

**Comment by zainfathoni** [comment]
Sounds good. Would you please update the issue description to match that approach, Mas @rubiagatra?

**Comment by zainfathoni** [comment]
> maybe we can use this kind of solution @zainfathoni ? 🤔  https://github.com/arduino/arduino-cli/pull/888/files

Sounds good. Would you please update the issue description to match that approach, Mas @rubiagatra?

> or yeah we need to create some documentation about disable actions https://github.community/t/stop-github-actions-running-on-a-fork/17965

We can also do this approach to educate our contributors in the meantime.

**Comment by rubiagatra** [comment]
Just updated TODO task and add separate issue for github action

**Comment by zainfathoni** [comment]
> Just updated TODO task and add separate issue for github action

You need to add a space between the brackets like this, Mas @rubiagatra. 😅
- [ ]

**Comment by rubiagatra** [comment]
lol ups 🤣 , done!
