### ISSUE TITLE
Lazy Loading Not Working

### ISSUE THREAD

**Issue by mazipan** [kawalcovid19/wargabantuwarga.com#760]
## Description

It's working on Chrome, but seems not working on My Firefox Developer Edition.

i try to test on web.dev/measure and it also not working:

- https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.wargabantuwarga.com%2F

## Expected Behaviour

It should not loaded when we test from web.dev/measure

## Additional Information

I already try to deep dive into Next/Image source code, they already use IntersectionObserver [see here](https://github.com/vercel/next.js/blob/canary/packages/next/client/image.tsx#L441)

**Comment by svspicious** [comment]
I think it's from `next/image`. It's also doesn't work here https://leerob.io/blog/style-guides-component-libraries-design-systems [(web.dev/measure report)](https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fleerob.io%2Fblog%2Fstyle-guides-component-libraries-design-systems#performance).

Same issue, it's working on my chrome but not working on my Firefox Dev and web.dev/measure .

**Comment by mazipan** [comment]
Do we need to wrap it inside our own IntersectionObserver?
But it might cause a layout shifting if we are not good in setting a correct high value.
Maybe try for the image on the very bottom of the page first.

We already have custom hooks `useIntersectionOberserver`, just in case if someone interest to try this out.

**Comment by svspicious** [comment]
I think it's working now, since #790 

https://user-images.githubusercontent.com/35674157/132293464-32adfa62-905f-4b28-805e-34f9f27048fc.mp4

Before (https://deploy-preview-788--wargabantuwarga.netlify.app/):

https://user-images.githubusercontent.com/35674157/132293618-b9f24783-024c-429e-aa15-04fccc671e79.mp4

**Comment by resir014** [comment]
Thank you @svspicious! I think it's safe to close this now. @kawalcovid19/wbw
