### ISSUE TITLE
[Mobile] Hero banner is missing in home page

### ISSUE THREAD

**Issue by josteph** [kawalcovid19/wargabantuwarga.com#768]
## Description

Only happens in mobile screen, desktop looks fine.

**Mobile**

https://res.cloudinary.com/wargabantuwarga/image/upload/c_scale,w_720,q_90,cs_tinysrgb,f_auto/hero_banner_desktop_zat71c

![image](https://user-images.githubusercontent.com/13672022/130027512-c404fffe-d916-40ba-8f98-e7067ee4827c.png)

**Desktop**

https://res.cloudinary.com/wargabantuwarga/image/upload/c_scale,w_720,q_90,cs_tinysrgb,f_auto/hero_banner_desktop_zat71c

![image](https://user-images.githubusercontent.com/13672022/130027626-247b7e87-a44f-4604-a78b-b7726b761aed.png)

## Expected Behaviour

Shows image correctly

## Additional Information

The image URL requested is the same https://res.cloudinary.com/wargabantuwarga/image/upload/c_scale,w_720,q_90,cs_tinysrgb,f_auto/hero_banner_desktop_zat71c but it isn't loading correctly on mobile screen

Response headers for **Mobile**

```
content-type: image/jp2
```

Response headers for **Desktop**

```
content-type: image/webp
```

**Comment by svspicious** [comment]
It seems, this only happens on devtools and only when I choose "apple" device type.

![image](https://user-images.githubusercontent.com/35674157/130031043-9eef7a0a-65a6-464b-8585-e1f59261b15c.png)

when I'm using "Responsive" it works
![image](https://user-images.githubusercontent.com/35674157/130031319-3d77a8f3-29d9-41df-b7f1-f6995559fc96.png)

I think we need real devices with small screen to reproduce this

**Comment by josteph** [comment]
The banner image is correctly displayed in iPhone 5S Safari as well.

Should we close this issue?

**Comment by svspicious** [comment]
Yes, i think we should.
it works as intended.
