### ISSUE TITLE
Missing Trustmed Logo on Officially Supported Apps

### ISSUE THREAD

**Issue by dekwahdimas** [kawalcovid19/wargabantuwarga.com#774]
## Description

![trustmed](https://user-images.githubusercontent.com/56619123/130321766-a1cce2b0-d302-461f-a1bb-62c717ba3247.png)

Trustmed Logo is missing.

## Expected Behaviour

Showed Trustmed Logo correctly.

**Comment by zainfathoni** [comment]
![image](https://user-images.githubusercontent.com/6315466/130322106-76129b15-f132-4472-b367-46bed30e9cfa.png)

Mas @mazipan or Mbak @ekafyi, could you please help with this issue?

**Comment by dekwahdimas** [comment]
I try to reupload it from CMS #775. The cloudinary images from [here](https://github.com/kawalcovid19/wargabantuwarga.com/issues/627#issuecomment-897720485).

Preview: https://deploy-preview-775--wargabantuwarga.netlify.app/

Preview looks cool, but it fails after published.

**Comment by ekafyi** [comment]
This is weird though.

The image in question was uploaded to Cloudinary via Netlify CMS, and it was deployed to an unusual (id?) path `dm3klplub`, not our default username path `wargabantuwarga`, as seen in https://github.com/kawalcovid19/wargabantuwarga.com/commit/5ec17651d9f6df24e415c87534e1fb1cb8079301

https://github.com/kawalcovid19/wargabantuwarga.com/blob/5ec17651d9f6df24e415c87534e1fb1cb8079301/_content/officially_supported_apps.json#L66

I did a quick check to try and reproduce it in    https://github.com/kawalcovid19/wargabantuwarga.com/pull/777/commits/c9780ce704fd870dbaa485c1cc80c57d1eae9577 but failed, it was deployed to the expected username path.

https://github.com/kawalcovid19/wargabantuwarga.com/blob/c9780ce704fd870dbaa485c1cc80c57d1eae9577/_content/officially_supported_apps.json#L71

Shall I create a separate issue to investigate this to prevent this issue happening in the future?

**Comment by mazipan** [comment]
Not just okay in the preview, before publishing something, please also quick check the PR first.
We have our own Cloudinary and didn't allow image from other Cloudinary account, it cause the next/image failed to work.
We can handle it via codebase, with adding a fallback if the the image is not coming from our Cloudinary account, but I think it useless.
But if we really want to support this kind of fallback, please help to create new issue.

We should always use WBW account in my opinion.
