### ISSUE TITLE
Implement `fetch-database.ts` to fetch from https://kcov.id/wbw-database

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#784]

**Comment by hanihusam** [comment]
Does this file have the same code context as the one in `fetch-sheets.ts`?

**Comment by zainfathoni** [comment]
> Does this file have the same code context as the one in `fetch-sheets.ts`?

Yes, practically, you can copy the `fetch-sheets.ts` file and modify it accordingly.
