### ISSUE TITLE
Use `fetch-database.ts` in `mirror-box.ts`

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#785]

**Comment by Namchee** [comment]
Is this being blocked by #784 ?

**Comment by zainfathoni** [comment]
> Is this being blocked by #784?

Yes, it is.

**Comment by zainfathoni** [comment]
I just unblocked #788 PR, so #784 is closed now.
You can start working on it if you want, @Namchee. Thanks! 🙏
