### ISSUE TITLE
Use the `wbw-database.json` data in the `Province` and `Contact` page according to the new logic

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#787]

**Comment by ermasavior** [comment]
Hello. I want to clarify the changes to be done in this issue. Please correct me if i missed something.

- Change data import in [`/lib/data/provinces.ts`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/provinces.ts#L1) into `wbw-database.json`
-  Update `Contact` data field in [`/lib/data/provinces.ts`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/provinces.ts#L12)
- Update [`provinces test`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/__tests__/provinces.test.ts) and [`mock`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/__mocks__/builders/provinces.ts)

And for this issue, do we need to add changes to the page view?
Thank you.

**Comment by zainfathoni** [comment]
> Hello. I want to clarify the changes to be done in this issue. Please correct me if i missed something.
> 
> * Change data import in [`/lib/data/provinces.ts`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/provinces.ts#L1) into `wbw-database.json`
> * Update `Contact` data field in [`/lib/data/provinces.ts`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/provinces.ts#L12)
> * Update [`provinces test`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/__tests__/provinces.test.ts) and [`mock`](https://github.com/kawalcovid19/wargabantuwarga.com/blob/823869631146094377d86925d14bb5b924a106ab/lib/data/__mocks__/builders/provinces.ts)
> 
> And for this issue, do we need to add changes to the page view?
> Thank you.

Yes, we need to change how the data is shown, according to the specification defined in #783.
