### ISSUE TITLE
Implement `fetch-vaccination-database.ts` to fetch data from https://api.vaksinasi.id/docs and store it into `wbw-vaccination-database.json` file

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#803]

**Comment by FortressValkyrie** [comment]
I have written some bits, just need to finish the test now, 'cuz TDD. I'm at school rn, and I didn't get to commit and push it before school so I'll just leave this message to let everyone know that they shouldn't work in this.
