### ISSUE TITLE
Add reporting button, to report any information that no longer relevant, or has poor quality.

### ISSUE THREAD

**Issue by baraeb92** [kawalcovid19/wargabantuwarga.com#83]
Description

As a user who is searching for relevant and high-quality information related to Covid-19, I want the wargabantuwarga to display the most accurate information only so that I don't waste time when trying to get in touch and use the information only to find out that the information is outdated or misleading. 

Acceptance Criteria

**Given that** a user who has information related to inaccuracy and poor quality of the information provided by Wargabantuwarga

**When users** found poor information, they can click on prominent laporkan data bermasalah on every FAQ page.

**Then the user** will be redirected to: https://docs.google.com/forms/d/e/1FAIpQLSeDdZLMD9RTfOiKMItNb8542KAO5w3x9O2ZFQmNyff1rYRZvQ/viewform

Require A QA To Test? 

Yes

## Implementation Model

There's an existing implementation already for the `ContactPage`.
Please refer to #138 as a reference.

## Tasks

- [ ] Create design for laporkan button on each FAQ page
- [ ] ...
- [ ] ...

**Comment by zainfathoni** [comment]
Google Forms has a feature to [prefill the form ahead](https://www.labnol.org/prefilled-google-forms-200601) based on the URL.

If we managed to deduce the URL format for prefilling the forms, we can reduce the frictions from the user by attaching the report button/CTA into each item and generating specific URLs for each item to prefill the form with the details from the particular item.

**Comment by baraeb92** [comment]
So in this case we need to add each parameter required and customized it based on the page where user click the report button ya mas @zainfathoni ?

**Comment by zainfathoni** [comment]
Yes, Mas @baraeb92. Please try to experiment with the form prefill feature to understand the pattern of the URLs.

If you need my help in experimenting with the patterns, please grant me edit access to the form so I can try it by myself.

**Comment by mazipan** [comment]
Is this still relevant, or do we need to close this issue?

**Comment by zainfathoni** [comment]
Yes, this issue is still relevant, because it is for the FAQ page. Our implementation on #138 was only for the Contact page.

**Comment by abui-am** [comment]
Any progress in this issue?

**Comment by mazipan** [comment]
Not yet mas @abui-am, do you wanna help on this?

**Comment by abui-am** [comment]
Sure @mazipan , I'll take a look 😃

**Comment by abui-am** [comment]
Quick question mas @mazipan ,
where is the FAQ page?

![image](https://user-images.githubusercontent.com/50738961/128604933-f30c8abb-1736-41d3-b245-769f7de43b7a.png)

Is this the FAQ page?

**Comment by mazipan** [comment]
https://www.wargabantuwarga.com/faq mas @abui-am

**Comment by abui-am** [comment]
> Then the user will be redirected to: https://docs.google.com/forms/d/e/1FAIpQLSeDdZLMD9RTfOiKMItNb8542KAO5w3x9O2ZFQmNyff1rYRZvQ/viewform

I have some problems here, I noticed most of our FAQ page information is general information.
while in the report form, we need to report wrong information "Province" and "Location",
this might confuse our user, should we create another form?

**Comment by abui-am** [comment]
I don't think we can report this
![image](https://user-images.githubusercontent.com/50738961/128659199-978f1e8c-9f2a-40d0-8de9-8f560e22871b.png)

In the current form
![image](https://user-images.githubusercontent.com/50738961/128659213-f2dc87f5-e250-47a4-a7d4-5223876184e5.png)

**Comment by zainfathoni** [comment]
I think need a new Google Form here, let me ask Mas @ardiwilda to prepare it.

**Comment by zainfathoni** [comment]
What's your Gmail address, @abui-am?
The form is ready, I can invite you as an editor so you can start working on it. 😁

**Comment by abui-am** [comment]
@zainfathoni Here is my email, adjiem31@gmail

**Comment by zainfathoni** [comment]
> @zainfathoni Here is my email, [adjiem31@gmail.com](mailto:adjiem31@gmail.com)

I just granted you edit access to the form, so you can start working on it, Mas @abui-am.
Would you please create a [draft pull request](https://kcov.id/draft-pr) when you start working on it? Thanks!
