### ISSUE TITLE
Implement search functionality in Database & Province page

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#86]

**Comment by ekamuktia** [comment]
It'll be great if there's filter based on Kebutuhan / Lokasi for easier access 

Plus, for better search result maybe full text search can be used?
Some library:
https://www.npmjs.com/package/itemsjs (with aggregation to support the filter)
https://www.npmjs.com/package/minisearch

**Comment by zainfathoni** [comment]
Sorry, I just read your comment right after I finished implementing and merging #88 😅 

I also learnt from @resir014 that there's another search library named [Fuse.js](https://fusejs.io).

I think they are good options to improve our current search functionality, and we can take a closer look at them and try to use them in our implementation as an enhancement on top of my basic implementation.

**Comment by zainfathoni** [comment]
Let's work on it at #110, thanks!
