### ISSUE TITLE
Implement top navigation and breadcrumbs

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#87]
## Description

Implement top navigation, breadcrumbs and page header to create a responsive, mobile-first design.

## Implementation Model

We'll use UI components from [Tailwind UI](https://tailwindui.com/)

## Tasks

- [ ] Application shell
- [ ] Page headers (with breadcrumbs
- [ ] Ensure all components are responsive (mobile-first)

**Comment by ekamuktia** [comment]
let me handle this issue

could you explain a bit more? @zainfathoni 
what i'm thinking it'll be like this:
- breadcrumbs in province/contact page
- top navigation in home page - links to FAQ, Province List Page

**Comment by resir014** [comment]
I'll take this. I'll grab some stuff from Tailwind UI as discussed by @zainfathoni and work on the following:

- Page headers
- Application shell (w/ navbar + footer)
