### ISSUE TITLE
Implement a dropdown filter based on `Kategori Pertanyaan`

### ISSUE THREAD

**Issue by zainfathoni** [kawalcovid19/wargabantuwarga.com#96]

**Comment by syauqy** [comment]
Hi Mas @zainfathoni, does the dropdown select will replace the search form inside the faq page?

![wbw dropdown 480](https://user-images.githubusercontent.com/3627108/126067315-771daf25-fd05-4e17-ac77-17698ff70cb8.gif)

Any advice on the filter?

**Comment by zainfathoni** [comment]
No, it shouldn't replace the search functionality.

Btw, there's already a Draft PR submitted for this issue #136.
If you're also working on it, please submit a Draft PR so we can see how much you're progressing with your implementation.
